"""Cast table and canvas policy.

The two id spaces in this project do not agree and one of the collisions is
live: national dex 25 is Pikachu, while game species id 25 is Rattata.  Every
lookup here goes through GAME_ID -> dex, never the other way round by
coincidence, and the mapping below is cross-checked against the original
artwork filenames (which encode the dex number: Pikachu was 002501.png).

The collision is not the exception, it is the rule.  Across the 53 species in
this cast only two -- Bulbasaur and Ivysaur -- have game id equal to dex, while
48 have a game id that is some *other* species' dex: game 16 is Butterfree
while dex 16 is Pidgey, and both are in this table at once.  Reading the wrong
column does not raise an error anywhere, it just hands over the wrong animal.
So the mapping is transcribed from the game's own registry
(Assets/StreamingAssets/pokelab/species.json), which stores `Id` and
`NationalDex` on the same record, rather than derived.  check_ids.py re-checks
every row against that registry and against the staged filenames.
"""

from __future__ import annotations

import os

SOURCE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "source")

# --------------------------------------------------------------------------
# canvas policy
# --------------------------------------------------------------------------
#
# 96x96 is not a choice so much as the format the source is already in: the
# static Gen 5 sprites are 96x96, and every animation canvas in the cast fits
# inside it.  Using anything else would mean rescaling official pixel art,
# which is the one thing this pipeline must never do.
#
# It is a real constraint, not a formality: widening the cast to 53 turned up
# nine species whose animations travel outside a 96x96 cell once their ground
# contact is pinned (mostly fliers and the very large -- Charizard, Golbat,
# Pidgeotto, Onix).  They are listed in BLOCKED below rather than squeezed in.
CELL = 96
COLS = 8

# Row that ground contact is pinned to, in every cell of every species and
# every view.  Leaves 11px below for creatures whose animation dips under
# their resting pose (Gastly, Zubat, Oddish all do) and 84 above for the tall
# ones.  Verified against the whole cast by extract.py, which fails loudly
# rather than silently clipping.
GROUND_ROW = 84

# 1 world unit = 1 metre, so a full 96px cell is one metre tall.  Gen 5 sprite
# sizes already track species size roughly, which lands Pikachu at ~0.48m
# against a true 0.40m -- close enough that no per-species fudge is needed.
# At 1080p integer magnifications of 4x/5x/6x are all clean.
PPU = 96

# Fits every front static in the cast, with 3px to spare: the largest that fits
# is Machoke at 56x69, then Machamp 63x68 and Pidgeot 55x68.  Six species are
# excluded by this box rather than by the animation canvas, and Poliwrath
# (80x57) is excluded by it alone -- see BLOCKED.
PORTRAIT = 72

# --------------------------------------------------------------------------
# the cast
# --------------------------------------------------------------------------
#
# (game species id, national dex, name, height in metres)
#
# Both ids and the height come from the game's own registry
# (Assets/StreamingAssets/pokelab/species.json), which carries `Id` (the
# KaggleID gameplay uses) and `NationalDex` side by side on the same record.
# That file is what resolves the collision rather than any reasoning about it:
# every row below was generated by looking up the species and reading both
# fields off it, so GAME_ID -> dex is transcribed, never inferred.  Heights are
# the registry's `Height` in decimetres divided by 10, which reproduced all
# twelve of the original entries exactly (Zubat 0.80 included).
#
# Ordered by game id, which is NOT dex order -- Ekans is game 29 / dex 23 while
# Pikachu is game 31 / dex 25.  Reading this table as if one column were the
# other is the failure this pipeline exists to prevent.
CAST = [
    (1,     1, "Bulbasaur",  0.70),
    (2,     2, "Ivysaur",    1.00),
    (5,     4, "Charmander", 0.60),
    (6,     5, "Charmeleon", 1.10),
    (10,    7, "Squirtle",   0.50),
    (11,    8, "Wartortle",  1.00),
    (12,    9, "Blastoise",  1.60),
    (14,   10, "Caterpie",   0.30),
    (15,   11, "Metapod",    0.70),
    (16,   12, "Butterfree", 1.10),
    (17,   13, "Weedle",     0.30),
    (18,   14, "Kakuna",     0.60),
    (19,   15, "Beedrill",   1.00),
    (21,   16, "Pidgey",     0.30),
    (23,   18, "Pidgeot",    1.50),
    (25,   19, "Rattata",    0.30),
    (26,   20, "Raticate",   0.70),
    (27,   21, "Spearow",    0.30),
    (29,   23, "Ekans",      2.00),
    (31,   25, "Pikachu",    0.40),
    (32,   26, "Raichu",     0.80),
    (33,   27, "Sandshrew",  0.60),
    (41,   35, "Clefairy",   0.60),
    (47,   41, "Zubat",      0.80),   # canonical Pokedex height
    (49,   43, "Oddish",     0.50),
    (50,   44, "Gloom",      0.80),
    (51,   45, "Vileplume",  1.20),
    (52,   46, "Paras",      0.30),
    (54,   48, "Venonat",    1.00),
    (56,   50, "Diglett",    0.20),
    (60,   54, "Psyduck",    0.80),
    (62,   56, "Mankey",     0.50),
    (64,   58, "Growlithe",  0.70),
    (66,   60, "Poliwag",    0.60),
    (67,   61, "Poliwhirl",  1.00),
    (69,   63, "Abra",       0.90),
    (73,   66, "Machop",     0.80),
    (74,   67, "Machoke",    1.50),
    (75,   68, "Machamp",    1.60),
    (76,   69, "Bellsprout", 0.70),
    (81,   74, "Geodude",    0.40),
    (82,   75, "Graveler",   1.00),
    (83,   76, "Golem",      1.40),
    (86,   79, "Slowpoke",   1.20),
    (95,   87, "Dewgong",    1.70),
    (100,  92, "Gastly",     1.30),
    (102,  94, "Gengar",     1.50),
    (107,  98, "Krabby",     0.40),
    (126, 116, "Horsea",     0.40),
    (128, 118, "Goldeen",    0.60),
    (130, 120, "Staryu",     0.80),
    (140, 129, "Magikarp",   0.90),
    (145, 133, "Eevee",      0.30),
]

BY_GAME_ID = {c[0]: c for c in CAST}

# --------------------------------------------------------------------------
# considered and deliberately left out
# --------------------------------------------------------------------------
#
# These nine have official Gen 5 artwork staged in source/ and correct ids, and
# they are still not in the cast: their artwork does not fit the canvas policy
# above, and the only ways to make it fit are to rescale the sprite or to move
# GROUND_ROW/CELL/PORTRAIT.  Rescaling is forbidden outright; moving the canvas
# constants would re-align the twelve species already shipped and verified.  So
# they are recorded here as a known gap rather than forced through.
#
# Two of them (Koffing, Seaking) are referenced by the level's roamer regions,
# so those references stay unfilled -- see the id-space note in the report.
#
# Measured by placing every animation frame at ground row 84 and asking how far
# outside the 96x96 cell it lands; portrait figures are the front static's
# trimmed bounding box against PORTRAIT.
BLOCKED = {
    # game_id: (dex, name, why)
    3:   (3,   "Venusaur",  "anim front overflows 1px right; front static 79x69 > 72 portrait"),
    7:   (6,   "Charizard", "anim front needs 4px more headroom, back 9px left; static 74x80 > 72"),
    22:  (17,  "Pidgeotto", "anim front needs 8px headroom and 13px below; static 68x80 > 72"),
    48:  (42,  "Golbat",    "anim front needs 10px left/4px right/4px below; static 80x62 > 72"),
    68:  (62,  "Poliwrath", "front static 80x57 > 72 portrait box (animation itself fits)"),
    101: (93,  "Haunter",   "anim back needs 2px left and 1px below"),
    104: (95,  "Onix",      "anim back overflows 25px right; static 72x73 > 72. 8.8m species"),
    118: (109, "Koffing",   "anim front dips 4px below the cell floor"),
    129: (119, "Seaking",   "anim back overflows 4px left"),
}


def anim_path(dex: int, view: str) -> str:
    return os.path.join(SOURCE_DIR, f"anim_{view}_{dex}.gif")


def static_path(dex: int, view: str) -> str:
    return os.path.join(SOURCE_DIR, f"{view}_{dex}.png")
