using System.Collections;
using System.Collections.Generic;
using PokeLab.Core;
using PokeLab.Overworld;
using Unity.Cinemachine;
using UnityEngine;
using UnityEngine.Playables;

namespace PokeLab.Cinematics.Sequencing
{
    /// <summary>
    /// The episode runner's camera department: composed, placed shots for the opening act's
    /// fixed choreography, where <c>OverworldCameraRig.LookToward</c> can only set a yaw.
    ///
    /// The diagnosed failure this replaces: a CameraTo beat kept the exploration rig's 8°
    /// pitch and 8.5 m boom and swung it — so the lab dome reveal cut the dome off above the
    /// frame, and the gate-ramp refusal framed dirt and a signpost because no yaw from the
    /// player's position can see down a ramp the camera is standing on top of. A shot has to
    /// be PLACED, and this class is what places it.
    ///
    /// It implements <see cref="IEpisodeShotDirector"/>, the contract the runner declares —
    /// the same forward-reference seam the rest of the project uses: Overworld owns the
    /// contract, Cinematics (which references Overworld) implements it, ServiceHub joins
    /// them, and the runner degrades to the yaw swing when nothing is registered.
    ///
    /// The camera is taken the way every camera in this project is taken: a
    /// <see cref="CinemachineCamera"/> claiming <see cref="ShotPriorities.EpisodeShot"/> and
    /// giving it back by dropping out, never by touching the real camera or the exploration
    /// rig. Two static-shot cameras alternate so a shot-to-shot change is a blend rather than
    /// a teleport of a live camera; a third carries the Timeline choreography. The dialogue
    /// two-shot at <see cref="ShotPriorities.Dialogue"/> outbids all of them for the length
    /// of a line and drops back — these cameras keep their state while outbid, which is what
    /// makes that safe.
    /// </summary>
    [DefaultExecutionOrder(-330)]
    [DisallowMultipleComponent]
    public sealed class EpisodeShotRig : MonoBehaviour, IEpisodeShotDirector
    {
        /// <summary>The runner resolves the player by this name; the orbit shots do too.</summary>
        private const string PlayerActorName = "Player";
        private const float DefaultFov = 40f;

        private static EpisodeShotRig _instance;

        private EpisodeShotBook _book;
        private bool _bookSearched;

        private readonly CinemachineCamera[] _staticCameras = new CinemachineCamera[2];
        private int _staticIndex;
        private CinemachineCamera _timelineCamera;
        private Animator _timelineAnimator;
        private PlayableDirector _director;
        private bool _timelinePlaying;
        private Coroutine _dolly;

        private readonly Dictionary<string, PlayableAsset> _timelineAssets =
            new Dictionary<string, PlayableAsset>();

        /// <summary>
        /// Stood up once per play session, with no scene wiring: the scenes are generated by
        /// the level builders, and a rig that must be hand-placed in every generated scene is
        /// a rig that is missing from one of them.
        /// </summary>
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static void Bootstrap()
        {
            if (_instance != null) return;
            var go = new GameObject("~EpisodeShotRig");
            DontDestroyOnLoad(go);
            go.AddComponent<EpisodeShotRig>();
        }

        private void Awake()
        {
            if (_instance != null && _instance != this)
            {
                Destroy(gameObject);
                return;
            }
            _instance = this;

            // The Timeline clips animate localPosition on children of this transform, and
            // local must equal world for the baked numbers to mean what shots.json says.
            transform.SetPositionAndRotation(Vector3.zero, Quaternion.identity);
            transform.localScale = Vector3.one;

            ServiceHub.Register<IEpisodeShotDirector>(this);

            // Subscribe, never assign — the multicast etiquette BattleCameraRig documents.
            CinemachineCore.GetBlendOverride += OnGetBlendOverride;
        }

        private void OnDestroy()
        {
            if (_instance == this) _instance = null;
            ServiceHub.Unregister<IEpisodeShotDirector>(this);
            CinemachineCore.GetBlendOverride -= OnGetBlendOverride;
        }

        /// <summary>
        /// Cuts instead of blending when the flight between two poses would go through the
        /// world.
        ///
        /// A Cinemachine blend moves the camera down the straight line between the outgoing
        /// and incoming poses, and this act stages shots across a town with a gorge in it:
        /// the opening's dome shot releases to an exploration camera standing on the south
        /// plaza, twenty-odd metres and one cliff away, and the player watched the camera
        /// dive through the hillside on the way back. No blend length fixes a path that is
        /// through rock — checked with a sphere cast between the two poses, plus a distance
        /// ceiling for flights that are merely absurd rather than blocked. This project
        /// avoids cuts as a rule; a camera inside the terrain is the exception that earns
        /// one. Pairs that do not involve this rig's cameras fall through untouched.
        /// </summary>
        private CinemachineBlendDefinition OnGetBlendOverride(
            ICinemachineCamera from, ICinemachineCamera to,
            CinemachineBlendDefinition defaultBlend, UnityEngine.Object owner)
        {
            if (!IsOurs(from) && !IsOurs(to)) return defaultBlend;

            if (!TryPosition(from, out var a) || !TryPosition(to, out var b)) return defaultBlend;

            var span = b - a;
            var distance = span.magnitude;
            if (distance > BlendCutDistance)
                return new CinemachineBlendDefinition(CinemachineBlendDefinition.Styles.Cut, 0f);

            if (distance > 0.5f && Physics.SphereCast(a, 0.25f, span / distance, out _,
                    distance - 0.4f, ~0, QueryTriggerInteraction.Ignore))
                return new CinemachineBlendDefinition(CinemachineBlendDefinition.Styles.Cut, 0f);

            return defaultBlend;
        }

        /// <summary>Beyond this, a blend is a flight across the map, not a transition.</summary>
        private const float BlendCutDistance = 20f;

        private bool IsOurs(ICinemachineCamera cam)
        {
            if (cam is not CinemachineCamera cm) return false;
            foreach (var mine in _staticCameras)
                if (mine != null && cm == mine) return true;
            return _timelineCamera != null && cm == _timelineCamera;
        }

        private static bool TryPosition(ICinemachineCamera cam, out Vector3 position)
        {
            if (cam is CinemachineCamera cm)
            {
                position = cm.transform.position;
                return true;
            }
            position = default;
            return false;
        }

        // --- IEpisodeShotDirector ------------------------------------------------------------

        public bool ShowShot(string shotName)
        {
            var shot = Book?.FindShot(shotName);
            if (shot == null)
            {
                Debug.LogWarning($"[Shots] No shot '{shotName}' in shots.json; the runner will " +
                                 "fall back to the yaw swing.", this);
                return false;
            }

            Vector3 position;
            Vector3 aimPoint;
            switch ((EpisodeShotMode)shot.Mode)
            {
                case EpisodeShotMode.Fixed:
                    if (!ShotMath.HasVector3(shot.Position) || !ShotMath.HasVector3(shot.LookAt))
                    {
                        Debug.LogWarning($"[Shots] '{shotName}' is Fixed but has no Position/" +
                                         "LookAt; falling back.", this);
                        return false;
                    }
                    position = ShotMath.ToVector3(shot.Position, Vector3.zero);
                    aimPoint = ShotMath.ToVector3(shot.LookAt, position + Vector3.forward);
                    break;

                case EpisodeShotMode.Orbit:
                    var target = string.IsNullOrEmpty(shot.TargetName)
                        ? null
                        : GameObject.Find(shot.TargetName);
                    if (target == null)
                    {
                        Debug.LogWarning($"[Shots] '{shotName}' orbits '{shot.TargetName}', " +
                                         "which is not in the scene; falling back.", this);
                        return false;
                    }
                    var player = GameObject.Find(PlayerActorName);
                    ShotMath.OrbitPose(shot, target.transform.position,
                        player != null ? player.transform.position : (Vector3?)null,
                        out position, out aimPoint);
                    break;

                default:
                    Debug.LogWarning($"[Shots] '{shotName}' has mode {shot.Mode}, which this rig " +
                                     "does not know; falling back.", this);
                    return false;
            }

            EnsureRig();
            StopDolly();
            if (_timelinePlaying) ForceFinishTimeline();

            // Alternate between the two static cameras so this transition — and the next —
            // is a Cinemachine blend between two poses rather than a cut inside one camera.
            _staticIndex = 1 - _staticIndex;
            var camera = _staticCameras[_staticIndex];
            camera.transform.SetPositionAndRotation(position, ShotMath.AimFrom(position, aimPoint));
            var lens = camera.Lens;
            lens.FieldOfView = shot.Fov > 1f ? shot.Fov : DefaultFov;
            camera.Lens = lens;

            Claim(camera);

            if (ShotMath.HasVector3(shot.DollyTo) && shot.DollySeconds > 0.01f)
            {
                _dolly = StartCoroutine(DollyRoutine(camera, position,
                    ShotMath.ToVector3(shot.DollyTo, position), aimPoint, shot.DollySeconds));
            }
            return true;
        }

        public void ReleaseShot()
        {
            StopDolly();
            if (_timelinePlaying) ForceFinishTimeline();
            Claim(null);
        }

        public float TimelineDurationSeconds(string timelineName)
        {
            var asset = LoadTimeline(timelineName);
            return asset != null ? (float)asset.duration : -1f;
        }

        /// <summary>
        /// Plays a generated TimelineAsset through the rig's own director, bound to the
        /// timeline camera, and blocks until it ends. The final frame is HELD: the camera
        /// stays claimed on the last pose so the beats after it play under the shot the
        /// choreography ended on, until the next shot replaces it or the episode releases.
        ///
        /// The runner wraps this in its bounded wait, so a director that never finishes is
        /// its problem to cut loose — via <see cref="ForceFinishTimeline"/>.
        /// </summary>
        public IEnumerator PlayTimeline(string timelineName)
        {
            var asset = LoadTimeline(timelineName);
            if (asset == null) yield break;

            EnsureRig();
            StopDolly();
            if (_timelinePlaying) ForceFinishTimeline();

            var definition = Book?.FindTimeline(timelineName);
            var lens = _timelineCamera.Lens;
            lens.FieldOfView = definition != null && definition.Fov > 1f ? definition.Fov : DefaultFov;
            _timelineCamera.Lens = lens;

            _director.playableAsset = asset;
            BindAnimatorOutputs(asset);
            _director.extrapolationMode = DirectorWrapMode.Hold;
            _director.time = 0.0;
            // Pose the camera at the first frame before it goes live, so the blend into the
            // timeline is a blend toward its authored opening pose and not toward wherever
            // the camera was left last time.
            _director.Evaluate();

            Claim(_timelineCamera);
            _timelinePlaying = true;
            _director.Play();

            var duration = (float)asset.duration;
            while (_timelinePlaying
                   && _director.state == PlayState.Playing
                   && _director.time < duration - 1e-3)
            {
                yield return null;
            }

            ForceFinishTimeline();
        }

        /// <summary>
        /// Jumps a playing timeline to its last frame and stops the graph, keeping the pose.
        /// Called on natural completion, on the runner's timeout, and when a new shot or a
        /// release arrives mid-play — in every case the camera must end where the author put
        /// it, never mid-move and never snapped back to the first frame.
        /// </summary>
        public void ForceFinishTimeline()
        {
            if (!_timelinePlaying) return;
            _timelinePlaying = false;
            if (_director == null || _director.playableAsset == null) return;

            _director.time = _director.playableAsset.duration;
            _director.Evaluate();

            // Stop() tears the graph down; whether the animated transform survives that is a
            // Unity implementation detail, so the pose is captured and put back explicitly.
            var body = _timelineCamera.transform;
            body.GetPositionAndRotation(out var position, out var rotation);
            _director.Stop();
            body.SetPositionAndRotation(position, rotation);
        }

        // --- Internals -----------------------------------------------------------------------

        private EpisodeShotBook Book
        {
            get
            {
                if (_bookSearched) return _book;
                _bookSearched = true;
                _book = EpisodeShotBook.Load();
                if (_book == null)
                    Debug.LogWarning("[Shots] No shots.json in Resources; every CameraShot beat " +
                                     "will degrade to the yaw swing.", this);
                return _book;
            }
        }

        private void EnsureRig()
        {
            if (_director != null) return;

            for (var i = 0; i < _staticCameras.Length; i++)
                _staticCameras[i] = BuildCamera($"CM_EpisodeShot_{(char)('A' + i)}", deoccluded: true);

            // No deoccluder on the timeline camera: its path is authored against verified
            // geometry, and a deoccluder would fight the animation with the animation winning
            // every frame — the worst of both.
            _timelineCamera = BuildCamera("CM_EpisodeShot_Timeline", deoccluded: false);
            _timelineAnimator = _timelineCamera.gameObject.AddComponent<Animator>();

            _director = gameObject.AddComponent<PlayableDirector>();
            _director.playOnAwake = false;
        }

        private CinemachineCamera BuildCamera(string cameraName, bool deoccluded)
        {
            var go = new GameObject(cameraName);
            go.transform.SetParent(transform, false);
            var cam = go.AddComponent<CinemachineCamera>();
            cam.Lens = LensSettings.Default;
            cam.Priority = 0;

            if (deoccluded)
            {
                // The OverworldCinematics pattern, verbatim: a placed overworld camera is the
                // easiest camera in the game to put inside a tree.
                var deoccluder = go.AddComponent<CinemachineDeoccluder>();
                var avoid = deoccluder.AvoidObstacles;
                avoid.Enabled = true;
                avoid.CameraRadius = 0.3f;
                avoid.Strategy = CinemachineDeoccluder.ObstacleAvoidance.ResolutionStrategy.PreserveCameraHeight;
                avoid.Damping = 0.4f;
                avoid.SmoothingTime = 0.2f;
                deoccluder.AvoidObstacles = avoid;
            }
            return cam;
        }

        /// <summary>
        /// Raises one camera to the episode-shot rung and drops the rest to nothing. Null
        /// drops them all, which is the release: the brain blends back to whatever the
        /// ladder says is next — exploration, usually.
        /// </summary>
        private void Claim(CinemachineCamera live)
        {
            foreach (var cam in _staticCameras)
                if (cam != null) cam.Priority = cam == live ? ShotPriorities.EpisodeShot : 0;
            if (_timelineCamera != null)
                _timelineCamera.Priority = _timelineCamera == live ? ShotPriorities.EpisodeShot : 0;
        }

        private void StopDolly()
        {
            if (_dolly == null) return;
            StopCoroutine(_dolly);
            _dolly = null;
        }

        private IEnumerator DollyRoutine(CinemachineCamera camera, Vector3 from, Vector3 to,
            Vector3 aimPoint, float seconds)
        {
            var elapsed = 0f;
            while (elapsed < seconds)
            {
                elapsed += Time.deltaTime;
                var s = Mathf.SmoothStep(0f, 1f, Mathf.Clamp01(elapsed / seconds));
                var position = Vector3.Lerp(from, to, s);
                camera.transform.SetPositionAndRotation(position,
                    ShotMath.AimFrom(position, aimPoint));
                yield return null;
            }
            _dolly = null;
        }

        private PlayableAsset LoadTimeline(string timelineName)
        {
            if (string.IsNullOrEmpty(timelineName)) return null;
            if (_timelineAssets.TryGetValue(timelineName, out var cached)) return cached;

            var asset = Resources.Load<PlayableAsset>(
                EpisodeShotBook.TimelineResourceFolder + "/" + timelineName);
            if (asset == null)
                Debug.LogWarning($"[Shots] No timeline '{timelineName}' under Resources/" +
                                 $"{EpisodeShotBook.TimelineResourceFolder}. Run Tools/Poké Lab/" +
                                 "Rebuild/Sequencing Timelines; the beat degrades until then.", this);
            _timelineAssets[timelineName] = asset;
            return asset;
        }

        /// <summary>
        /// Binds every Animator-typed track output to the timeline camera's Animator. The
        /// generated assets carry exactly one animation track; binding by output type rather
        /// than by name means a renamed track cannot silently unbind the camera.
        /// </summary>
        private void BindAnimatorOutputs(PlayableAsset asset)
        {
            foreach (var output in asset.outputs)
            {
                if (output.outputTargetType == typeof(Animator) && output.sourceObject != null)
                    _director.SetGenericBinding(output.sourceObject, _timelineAnimator);
            }
        }
    }
}
