#!/usr/bin/env python3
"""Regenerates Server/pokelab-online/src/learnsets.ts.

WHY THE WORKER NEEDS LEARNSETS AT ALL
-------------------------------------
A move disc (기술 디스크) is taught to one creature and then that creature fights a real
person in PvP.  Anything that changes a moveset therefore has to be decided by the server,
for the same reason the roster is: a moveset the client could choose is a moveset that means
nothing across the network.  And the rule the user asked for --

    막 모든 포켓몬이 막 모든 디스크를 배울 수 있다 X

-- is exactly a learnset lookup.  So the lookup has to exist on the Worker.

WHAT IS SHIPPED, AND WHAT IS NOT
--------------------------------
Only the species in the gacha pool.  The dex holds 721 learnsets and the pool holds 53,
because the pool is the species that have artwork -- see pool.ts.  A creature outside the
pool cannot be owned, so its learnset could never be consulted.  That is the difference
between ~7,000 rows and ~800, and it is what keeps the Worker script small.

The move ids are the same strings moves.json uses, which are the same strings
`PokeLab.Core.IMoveRegistry` keys on, so a disc id round-trips between the two runtimes
without a mapping table.

    python Tools/Export/gen_worker_learnsets.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MOVES = ROOT / "Assets" / "StreamingAssets" / "pokelab" / "moves.json"
POOL = ROOT / "Server" / "pokelab-online" / "src" / "pool.ts"
OUT = ROOT / "Server" / "pokelab-online" / "src" / "learnsets.ts"

HEADER = '''// GENERATED by Tools/Export/gen_worker_learnsets.py from
// Assets/StreamingAssets/pokelab/moves.json, restricted to the species in pool.ts.
//
// Do not hand-edit.  Rerun the generator after moves.json or the pool changes.
//
// This is the server's copy of one rule, and it is the rule the user asked for in as many
// words: 막 모든 포켓몬이 막 모든 디스크를 배울 수 있다 X.  A move disc may only be taught to a
// species whose learnset contains that move.  It lives here rather than only on the client
// because a taught move goes into PvP, and everything a PvP opponent's team is made of has to
// be something the opponent could not simply choose.
//
// Levels are kept because the default four moves are derived from them -- the same rule
// `PokeLab.PokeLab.Data.MoveRegistry.MovesFor` uses on the client: everything learned at or
// below the creature's level, latest four, a relearn keeping its newer slot.  Both runtimes
// have to agree about a creature's moveset for the same reason both have to agree about its
// level.
'''


def main() -> int:
    if not MOVES.exists():
        print(f"missing {MOVES}", file=sys.stderr)
        return 1
    if not POOL.exists():
        print(f"missing {POOL}", file=sys.stderr)
        return 1

    pool_ids = [int(m) for m in re.findall(r"speciesId:\s*(\d+)", POOL.read_text(encoding="utf-8"))]
    if not pool_ids:
        print("pool.ts yielded no species ids -- has its shape changed?", file=sys.stderr)
        return 1

    data = json.loads(MOVES.read_text(encoding="utf-8"))
    known = {move["Id"] for move in data["Moves"]}
    sets = {entry["SpeciesId"]: entry["Entries"] for entry in data["Learnsets"]}

    lines: list[str] = [HEADER]
    lines.append("/** moveId -> the level it is learned at, per species in the pool. */")
    lines.append("export const LEARNSETS: Record<number, Array<[string, number]>> = {")

    total = 0
    distinct: set[str] = set()
    for species in sorted(pool_ids):
        entries = sets.get(species)
        if not entries:
            print(f"  warning: pool species {species} has no learnset", file=sys.stderr)
            continue
        pairs = []
        for entry in entries:
            move = entry["MoveId"]
            if move not in known:
                print(f"  warning: species {species} references unknown move {move}", file=sys.stderr)
                continue
            pairs.append((move, int(entry.get("Level", 1))))
            distinct.add(move)
        total += len(pairs)
        body = ", ".join(f'["{move}", {level}]' for move, level in pairs)
        lines.append(f"  {species}: [{body}],")

    lines.append("};")
    lines.append("")
    lines.append("/** Every move any owned species can learn -- the disc pool. */")
    lines.append("export const TEACHABLE_MOVES: string[] = [")
    for move in sorted(distinct):
        lines.append(f'  "{move}",')
    lines.append("];")
    lines.append("")
    lines.append(TAIL)

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(pool_ids)} species, {total} entries, "
          f"{len(distinct)} distinct moves")
    return 0


TAIL = '''/** True when this species may be taught this move. The whole point of the file. */
export function canLearn(speciesId: number, moveId: string): boolean {
  const set = LEARNSETS[speciesId];
  if (!set) return false;
  return set.some(([move]) => move === moveId);
}

/**
 * The four moves a creature of this species and level knows by default.
 *
 * Deliberately the same rule as the client's `MoveRegistry.MovesFor`: walk the learnset in
 * level order, keep everything learned at or below `level`, drop the oldest once there are
 * more than four, and let a relearned move take the newer slot.  The two implementations are
 * duplicated rather than shared because they run on different runtimes -- and duplicated with
 * this note, so whoever changes one has been told the other exists.
 */
export function defaultMoves(speciesId: number, level: number): string[] {
  const set = LEARNSETS[speciesId];
  if (!set) return [];

  const ordered = [...set].sort((a, b) => a[1] - b[1]);
  const known: string[] = [];
  for (const [move, at] of ordered) {
    if (at > level) break;
    const seen = known.indexOf(move);
    if (seen >= 0) known.splice(seen, 1);
    known.push(move);
    if (known.length > 4) known.shift();
  }
  return known;
}
'''


if __name__ == "__main__":
    raise SystemExit(main())
