using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using NUnit.Framework;
using PokeLab.Core;
using PokeLab.Intelligence;
using PokeLab.Intelligence.Data;
using PokeLab.Intelligence.Model;
using UnityEngine;

namespace PokeLab.Tests
{
    /// <summary>
    /// Checks the C# forest port against values produced by the upstream Python
    /// backend.py. The expectations below are not hand-written: they were generated by
    /// Tools/Export/gen_reference.py and pasted in, so this test failing means the port and
    /// the source model have genuinely diverged.
    ///
    /// Tolerance is 1e-4. The observed worst case across these pairs is about 3e-8, which
    /// is float32 storage of the probability rather than any difference in the maths.
    /// </summary>
    [TestFixture]
    public sealed class PokeLabOracleTests
    {
        private const double Tolerance = 1e-4;

        private static PokeLabData _data;
        private static ForestOracle _oracle;

        /// <summary>
        /// Expected values from backend.py: first id, second id, P(first wins).
        /// Regenerate with:  .venv/Scripts/python.exe Tools/Export/gen_reference.py
        /// </summary>
        private static readonly (int First, int Second, double Probability)[] Expected =
        {
            (1, 5, 0.001041666666666663),      // Bulbasaur vs Charmander
            (5, 10, 0.9874851190476189),       // Charmander vs Squirtle
            (10, 21, 0.007361111111111096),    // Squirtle vs Pidgey
            (21, 25, 0.011236772486772573),    // Pidgey vs Rattata
            (25, 31, 0.020913600288600287),    // Rattata vs Pikachu
            (31, 47, 0.9873809523809525),      // Pikachu vs Zubat
            (47, 49, 0.9573063973063973),      // Zubat vs Oddish
            (49, 66, 0.1319025765900766),      // Oddish vs Poliwag
            (66, 73, 0.8891914682539681),      // Poliwag vs Machop
            (73, 81, 0.9723359279609279),      // Machop vs Geodude
            (81, 100, 0.7684740201927702),     // Geodude vs Gastly
            (100, 1, 0.9083685064935063),      // Gastly vs Bulbasaur
            (100, 81, 0.23152597980722978),    // Gastly vs Geodude (mirror of the above)
            (31, 81, 0.34419598919598915),     // Pikachu vs Geodude - Electric is 0x here
            (81, 31, 0.6558040108040106),      // Geodude vs Pikachu
            (1, 1, 0.5),                       // mirror match
            (73, 21, 0.0419042358104858),      // Machop vs Pidgey
            (100, 25, 0.8511248242498242),     // Gastly vs Rattata - Ghost/Normal both ways
            (47, 73, 0.9275015384941857),      // Zubat vs Machop
            (10, 1, 0.009338624338624313),     // Squirtle vs Bulbasaur
            (66, 31, 0.49023809523809525),     // Poliwag vs Pikachu - the closest matchup
            (49, 5, 0.006329365079365101),     // Oddish vs Charmander
            (146, 1, 0.9441475769600768),      // Vaporeon vs Bulbasaur
            (445, 100, 0.3282517366892368),    // Bidoof vs Gastly
            (400, 81, 0.974751984126984),      // Sealeo vs Geodude
            (697, 1, 0.9850243506493507),      // Hydreigon vs Bulbasaur
            (1, 697, 0.014975649350649378),    // Bulbasaur vs Hydreigon
        };

        [OneTimeSetUp]
        public void LoadExportedData()
        {
            var root = Path.Combine(Application.streamingAssetsPath, PokeLabData.Files.Directory);
            if (!Directory.Exists(root))
                Assert.Ignore($"Poké Lab data not exported yet ({root}). Run Tools/Export/export_pokelab.py.");

            _data = PokeLabData.Parse(
                File.ReadAllText(Path.Combine(root, PokeLabData.Files.Species), Encoding.UTF8),
                File.ReadAllText(Path.Combine(root, PokeLabData.Files.Moves), Encoding.UTF8),
                File.ReadAllText(Path.Combine(root, PokeLabData.Files.TypeChart), Encoding.UTF8),
                File.ReadAllBytes(Path.Combine(root, PokeLabData.Files.Forest)),
                File.ReadAllBytes(Path.Combine(root, PokeLabData.Files.Combats)));

            _oracle = new ForestOracle(_data.Forest, _data.Species, _data.TypeChart, _data.Combats);
        }

        // --- Data integrity -----------------------------------------------------------

        [Test]
        public void ExportedForestHasTheExpectedShape()
        {
            Assert.AreEqual(120, _data.Forest.TreeCount, "tree count");
            Assert.AreEqual(11, _data.Forest.FeatureCount, "feature count");
            Assert.AreEqual(264814, _data.Forest.NodeCount, "total node count");
        }

        [Test]
        public void ExportedDexCoversEverySpecies()
        {
            // 697 from the upstream Kaggle dex, plus the 24 its merge dropped and
            // Tools/Export/species_supplement.csv puts back. National dex 1-721, no gaps.
            Assert.AreEqual(721, _data.Species.Count);
            foreach (var id in new[] { 1, 5, 10, 21, 25, 31, 47, 49, 66, 73, 81, 100 })
                Assert.IsTrue(_data.Species.TryGet(id, out _), $"slice species {id} missing");

            var seen = new bool[722];
            foreach (var entry in _data.Species.All)
            {
                Assert.IsTrue(entry.NationalDex >= 1 && entry.NationalDex <= 721,
                              $"species {entry.Id} ({entry.NameEn}) has dex {entry.NationalDex}, outside 1-721");
                Assert.IsFalse(seen[entry.NationalDex], $"national dex {entry.NationalDex} appears twice");
                seen[entry.NationalDex] = true;
            }
            for (var dex = 1; dex <= 721; dex++) Assert.IsTrue(seen[dex], $"national dex {dex} missing");

            // Ids are KaggleIDs, not dex numbers. Aegislash is #681 and id 752; reading one
            // as the other is the mistake this dex makes easiest and reports latest.
            Assert.IsTrue(_data.Species.TryGet(752, out var aegislash), "Aegislash (id 752) missing");
            Assert.AreEqual(681, aegislash.NationalDex);
        }

        [Test]
        public void TypeChartMatchesTheSourceDomainTable()
        {
            var chart = _data.TypeChart;
            Assert.AreEqual(2f, chart.Multiplier(ElementType.Water, ElementType.Fire), 1e-6f);
            Assert.AreEqual(0f, chart.Multiplier(ElementType.Electric, ElementType.Ground), 1e-6f);
            Assert.AreEqual(0f, chart.Multiplier(ElementType.Normal, ElementType.Ghost), 1e-6f);
            Assert.AreEqual(0.5f, chart.Multiplier(ElementType.Grass, ElementType.Fire), 1e-6f);
            // Water into Geodude's Rock/Ground stacks to 4x, which is the slice's signature
            // matchup and the one the scanner quotes most.
            Assert.AreEqual(4f, chart.Multiplier(ElementType.Water, ElementType.Rock, ElementType.Ground), 1e-6f);
        }

        [Test]
        public void DefensiveAbilityModifiersLoad()
        {
            var chart = _data.TypeChart;
            Assert.AreEqual(0f, chart.AbilityModifier("levitate", ElementType.Ground), 1e-6f);
            Assert.AreEqual(0.5f, chart.AbilityModifier("thick-fat", ElementType.Fire), 1e-6f);
            Assert.AreEqual(1.25f, chart.AbilityModifier("dry-skin", ElementType.Fire), 1e-6f);
            Assert.AreEqual(1f, chart.AbilityModifier("overgrow", ElementType.Fire), 1e-6f);
        }

        // --- The port -----------------------------------------------------------------

        [Test]
        public void ProbabilitiesMatchPythonBackend()
        {
            var worst = 0d;
            var worstPair = string.Empty;

            foreach (var (first, second, expected) in Expected)
            {
                var actual = _oracle.Predict(first, second).FirstWinProbability;
                var delta = Math.Abs(actual - expected);
                if (delta > worst)
                {
                    worst = delta;
                    worstPair = $"{first} vs {second}";
                }
                Assert.AreEqual(expected, actual, Tolerance, $"P({first} beats {second})");
            }

            Debug.Log($"[PokeLab] max |C# - Python| = {worst:E3} over {Expected.Length} pairs (worst: {worstPair})");
            Assert.Less(worst, Tolerance, "worst-case drift across all reference pairs");
        }

        [Test]
        public void ReadoutIsOrderInvariant()
        {
            var ids = new[] { 1, 5, 10, 21, 25, 31, 47, 49, 66, 73, 81, 100, 146, 445 };
            foreach (var first in ids)
            {
                foreach (var second in ids)
                {
                    if (first == second) continue;
                    var forward = _oracle.Predict(first, second).FirstWinProbability;
                    var backward = _oracle.Predict(second, first).FirstWinProbability;
                    Assert.AreEqual(forward, 1f - backward, 1e-5f,
                        $"P({first},{second}) and P({second},{first}) disagree");
                }
            }
        }

        [Test]
        public void EvidenceIsCompleteAndSortedByContribution()
        {
            var prediction = _oracle.Predict(66, 81);
            Assert.AreEqual(11, prediction.Evidence.Length, "one entry per model feature");

            var seen = new HashSet<string>();
            for (var i = 0; i < prediction.Evidence.Length; i++)
            {
                var item = prediction.Evidence[i];
                Assert.IsTrue(seen.Add(item.Feature), $"duplicate feature {item.Feature}");
                Assert.IsNotEmpty(item.Label, "evidence needs a player-facing label");
                if (i > 0)
                {
                    Assert.GreaterOrEqual(
                        Math.Abs(prediction.Evidence[i - 1].ProbabilityPoints),
                        Math.Abs(item.ProbabilityPoints),
                        "evidence must be sorted by descending absolute contribution");
                }
            }
        }

        [Test]
        public void SameSpeciesIsAnEvenMatchWithNoEvidence()
        {
            var prediction = _oracle.Predict(25, 25);
            Assert.AreEqual(0.5f, prediction.FirstWinProbability, 1e-6f);
            Assert.IsEmpty(prediction.Evidence, "a mirror match has nothing to explain");
        }

        [Test]
        public void ImmunityAbilityRaisesTheExpectedWarning()
        {
            // Gastly's levitate blocks Geodude's Ground attacks; backend.py raises the same
            // caveat, and the scanner has to surface it.
            var prediction = _oracle.Predict(81, 100);
            var found = false;
            foreach (var warning in prediction.Warnings)
                if (warning.Contains("nullify") && warning.Contains("Ground")) found = true;
            Assert.IsTrue(found, "expected a Ground-immunity warning from Gastly's levitate");
        }

        [Test]
        public void TypeEffectsAreReportedBothWays()
        {
            // Water into Rock/Ground is 4x; Rock into Water is neutral at 1x.
            var prediction = _oracle.Predict(66, 81);
            Assert.AreEqual(4f, prediction.TypeEffectFirst, 1e-5f);
            Assert.AreEqual(1f, prediction.TypeEffectSecond, 1e-5f);
        }

        [Test]
        public void HistoricalRecordIsSymmetric()
        {
            var forward = _oracle.Predict(1, 5);
            var backward = _oracle.Predict(5, 1);
            Assert.AreEqual(forward.DirectBattles, backward.DirectBattles);
            Assert.AreEqual(forward.DirectFirstWins, backward.DirectSecondWins);
            Assert.AreEqual(forward.DirectSecondWins, backward.DirectFirstWins);
        }

        // --- Move pool ----------------------------------------------------------------

        [Test]
        public void MovePoolCoversTheSliceRoster()
        {
            Assert.GreaterOrEqual(_data.Moves.All.Count, 24, "the slice needs at least 24 moves");
            Assert.LessOrEqual(_data.Moves.All.Count, 32, "the slice was scoped at 32 moves");

            foreach (var speciesId in new[] { 1, 5, 10, 21, 25, 31, 47, 49, 66, 73, 81, 100 })
            {
                var learned = _data.Moves.MovesFor(speciesId, 20);
                Assert.IsNotEmpty(learned, $"species {speciesId} has no learnset");
                Assert.LessOrEqual(learned.Count, 4, $"species {speciesId} exceeded four moves");
                foreach (var move in learned)
                    Assert.IsNotNull(move.Id, "learnset returned a null move");
            }
        }

        [Test]
        public void LearnsetsGrowWithLevel()
        {
            var early = _data.Moves.MovesFor(1, 1);
            var later = _data.Moves.MovesFor(1, 20);
            Assert.AreEqual(2, early.Count, "Bulbasaur starts with Tackle and Growl");
            Assert.AreEqual(4, later.Count, "and is full by level 20");
        }

        [Test]
        public void MoveDataCarriesPresentationHints()
        {
            Assert.IsTrue(_data.Moves.TryGet("water-gun", out var waterGun));
            Assert.AreEqual(ElementType.Water, waterGun.Type);
            Assert.AreEqual(MoveCategory.Special, waterGun.Category);
            Assert.AreEqual(40, waterGun.Power);
            Assert.IsTrue(waterGun.IsProjectile);
            Assert.IsFalse(waterGun.MakesContact);
            Assert.IsNotEmpty(waterGun.VfxKey);
            Assert.IsNotEmpty(waterGun.AnimationKey);

            Assert.IsTrue(_data.Moves.TryGet("rock-blast", out var rockBlast));
            Assert.AreEqual(2, rockBlast.MinHits);
            Assert.AreEqual(5, rockBlast.MaxHits);

            Assert.IsTrue(_data.Moves.TryGet("absorb", out var absorb));
            Assert.AreEqual(0.5f, absorb.DrainRatio, 1e-6f);

            Assert.IsTrue(_data.Moves.TryGet("thunder-wave", out var thunderWave));
            Assert.AreEqual(StatusCondition.Paralysis, thunderWave.InflictsStatus);
            Assert.AreEqual(MoveCategory.Status, thunderWave.Category);

            Assert.IsTrue(_data.Moves.TryGet("quick-attack", out var quickAttack));
            Assert.AreEqual(1, quickAttack.Priority);
        }
    }
}
