# -*- coding: utf-8 -*-
"""Brings authored per-move sound effects into the project, and replaces the synthesised
battle system cues with real ones.

WHY THIS EXISTS. Every sound in Assets/Game/Audio was generated by the scripts beside this one
(sfx.py, music.py) — sine stacks and noise bursts standing in for a real library. They are
per-TYPE, not per-move: one Electric_Cast and one Electric_Impact serve Thunder Shock,
Thunderbolt and Thunder Wave alike. The user supplied a real library and asked for the lot to be
replaced ("사운드 이펙트 전면 수정").

WHAT IT TAKES, AND WHAT IT LEAVES. The source folder holds 620 files, ~108 MB, one per move in
the whole series. This game has THIRTY-TWO moves. Importing all 620 would more than double a
WebGL build that is already 66 MB, to ship 588 sounds nothing can ever play. So this takes only
what moves.json actually names — 32 of them, every one matched — plus the six In-Battle system
cues, and converts them to the format the rest of the catalogue already uses: 44.1 kHz, mono,
16-bit, peak-normalised to -1 dBFS. About 14 MB.

The per-type sounds are NOT deleted. They stay as the fallback for any move added later that has
no dedicated file, so a new move is quieter than it could be rather than silent.

Run from the repo root:
    python Tools/Audio/import_move_sfx.py            # convert and rewrite the manifest
    python Tools/Audio/import_move_sfx.py --dry-run  # report the mapping and change nothing

Afterwards, in Unity: Tools/Poke Lab/Audio/Reapply Import Settings, then Rebuild Catalogue,
then Validate Catalogue. The manifest is the catalogue's single source of truth, so a clip added
here is inert until that rebuild runs.
"""
import argparse
import io
import json
import os
import re
import subprocess
import sys

# Three levels: this file is Tools/Audio/import_move_sfx.py, so the repo root is three
# dirnames up, not two. Two lands on Tools/ and every path below it silently misses.
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# "바탕 화면" with the space is what Windows actually names the Korean desktop; the
# space-less spelling is the one everybody types and it does not exist on disk.
SOURCE = os.path.join(os.path.expanduser("~"), "바탕 화면", "soundeffect")
OUT_DIR = os.path.join(REPO, "Assets", "Game", "Audio", "SFX")
MANIFEST = os.path.join(REPO, "Assets", "Game", "Audio", "audio_manifest.json")
MOVES = os.path.join(REPO, "Assets", "StreamingAssets", "pokelab", "moves.json")

# The six system cues, and which existing catalogue entry each one replaces. Three of these
# names already exist and are being overwritten in place; three are new.
SYSTEM = [
    ("In-Battle Faint No Health.mp3", "SFX_Battle_Faint", False,
     "CreatureFaintedEvent."),
    ("In-Battle Recall Switch Pokeball.mp3", "SFX_Battle_Recall", False,
     "CreatureWithdrawnEvent, and the recall after an owned creature faints."),
    ("In-Battle Health Low Loop.mp3", "SFX_Battle_LowHpWarning", True,
     "Loops while the active player creature is below 20% HP; stops on heal or faint."),
    ("In-Battle Heal HP Restore.mp3", "SFX_Battle_HealRestore", False,
     "HP restored in battle: an item, a drain move, or the RestoreParty beat."),
    ("In-Battle Switch Flee Run.mp3", "SFX_Battle_Flee", False,
     "The player successfully runs from a wild encounter."),
    ("In-Battle Held Item Activate.mp3", "SFX_Battle_HeldItem", False,
     "A held item fires mid-battle."),
]


def clip_name_for(move_id):
    """SFX_Move_QuickAttack from quick-attack. Pascal case, so it reads in the catalogue."""
    return "SFX_Move_" + "".join(p.capitalize() for p in re.split(r"[-_ ]+", move_id) if p)


def find_source(name, index):
    """
    The file for a move, allowing for the two shapes the library uses for multi-stage moves.

    A move whose animation has stages is split into 'X part 1'/'X part 2', and a multi-hit move
    into 'X 1hit'/'X 2hits'. The first stage is the one that plays on the strike, so it is what
    a single-cue game wants.
    """
    key = name.lower()
    for candidate in (key, key.replace("-", " "),
                      key + " part 1", key.replace("-", " ") + " part 1",
                      key + " 1hit", key.replace("-", " ") + " 1hit"):
        if candidate in index:
            return index[candidate]
    return None


def measure(path):
    """Peak and mean dBFS, via ffmpeg's volumedetect."""
    done = subprocess.run(["ffmpeg", "-i", path, "-af", "volumedetect", "-f", "null", "-"],
                          capture_output=True, text=True, encoding="utf-8", errors="ignore")
    err = done.stderr or ""
    peak = re.search(r"max_volume: (-?[\d.]+) dB", err)
    mean = re.search(r"mean_volume: (-?[\d.]+) dB", err)
    return (float(peak.group(1)) if peak else 0.0,
            float(mean.group(1)) if mean else -20.0)


def duration_of(path):
    done = subprocess.run(["ffprobe", "-v", "quiet", "-show_entries", "format=duration",
                           "-of", "csv=p=0", path], capture_output=True, text=True)
    try:
        return round(float((done.stdout or "0").strip()), 4)
    except ValueError:
        return 0.0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not os.path.isdir(SOURCE):
        print("Source folder not found: %s" % SOURCE)
        return 1

    files = [f for f in os.listdir(SOURCE) if f.lower().endswith(".mp3")]
    index = {os.path.splitext(f)[0].lower(): f for f in files}

    raw = json.load(io.open(MOVES, encoding="utf-8"))
    moves = raw if isinstance(raw, list) else (raw.get("Moves") or list(raw.values())[0])

    jobs, missing = [], []
    for move in moves:
        name = (move.get("NameEn") or "").strip()
        source = find_source(name, index)
        if not source:
            missing.append(name)
            continue
        jobs.append((source, clip_name_for(move["Id"]), "SFX/Move", False,
                     "Move impact for '%s'." % move["Id"]))

    for source, out, loop, trigger in SYSTEM:
        if source in files:
            jobs.append((source, out, "SFX/Battle", loop, trigger))
        else:
            missing.append(source)

    print("%d move(s) in moves.json, %d matched, %d job(s) total"
          % (len(moves), len(moves) - len([m for m in missing if not m.startswith("In-Battle")]),
             len(jobs)))
    if missing:
        print("NO SOURCE FOR: %s" % ", ".join(missing))

    if args.dry_run:
        for source, out, _, _, _ in jobs:
            print("  %-34s -> %s.wav" % (source, out))
        return 0

    os.makedirs(OUT_DIR, exist_ok=True)
    written = []
    for source, out, category, loop, trigger in jobs:
        src_path = os.path.join(SOURCE, source)
        out_path = os.path.join(OUT_DIR, out + ".wav")

        peak, _ = measure(src_path)
        # Peak-normalise to -1 dBFS, which is what every existing clip in the manifest sits at.
        # Without this the imported library is markedly louder than the generated cues it is
        # mixed against, and the first thing anyone would do is turn the game down.
        gain = -1.0 - peak
        subprocess.run(["ffmpeg", "-y", "-v", "error", "-i", src_path,
                        "-af", "volume=%.2fdB" % gain,
                        "-ac", "1", "-ar", "44100", "-sample_fmt", "s16", out_path], check=True)

        new_peak, new_mean = measure(out_path)
        written.append({
            "name": out,
            "path": "Assets/Game/Audio/SFX/%s.wav" % out,
            "category": category,
            "loop": loop,
            "duration": duration_of(out_path),
            "channels": 1,
            "sample_rate": 44100,
            "bit_depth": 16,
            "peak_dbfs": round(new_peak, 2),
            "rms_dbfs": round(new_mean, 2),
            "bytes": os.path.getsize(out_path),
            "loop_step_ratio": 0.0 if loop else None,
            "trigger": trigger,
        })

    manifest = json.load(io.open(MANIFEST, encoding="utf-8"))
    by_name = {entry["name"]: i for i, entry in enumerate(manifest["clips"])}
    replaced = added = 0
    for entry in written:
        if entry["name"] in by_name:
            manifest["clips"][by_name[entry["name"]]] = entry
            replaced += 1
        else:
            manifest["clips"].append(entry)
            added += 1

    manifest["clips"].sort(key=lambda e: e["name"])
    json.dump(manifest, io.open(MANIFEST, "w", encoding="utf-8", newline="\n"),
              ensure_ascii=False, indent=2)

    total = sum(e["bytes"] for e in written)
    print("wrote %d clip(s): %d replaced, %d added, %.1f MB"
          % (len(written), replaced, added, total / 1048576.0))
    print("Now run, in Unity: Tools/Poke Lab/Audio/Reapply Import Settings, "
          "then Rebuild Catalogue, then Validate Catalogue.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
