# -*- coding: utf-8 -*-
"""Replaces the synthesised music loops with authored tracks.

The pieces the project had for battle, victory and the opening were generated by music.py
beside this file — eleven-second loops of stacked oscillators, standing in until real music
existed. The user supplied real recordings.

KEPT AS MP3, DELIBERATELY. Every other clip in this project is 16-bit WAV and this breaks that
pattern on purpose: these are three-to-four minute pieces, and at 44.1 kHz stereo a WAV of one
is about 40 MB. Five of them would add well over 100 MB to a WebGL build that is already 66 MB,
for audio the browser is going to re-compress anyway. As MP3 they total about 20 MB.
Unity imports MP3 as an AudioClip exactly as it does WAV; the manifest's `path` is only a string
and does not care about the extension.

They are peak-normalised to -1 dBFS to sit at the same level as the rest of the catalogue —
without it the imported tracks are markedly louder than the generated cues they play against.

Run from the repo root:
    python Tools/Audio/import_music.py
    python Tools/Audio/import_music.py --dry-run

Afterwards, in Unity: Tools/Poke Lab/Audio/Reapply Import Settings, then Rebuild Catalogue,
then Validate Catalogue. The manifest is the catalogue's source of truth.
"""
import argparse
import io
import json
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DOWNLOADS = os.path.join(os.path.expanduser("~"), "Downloads")
OUT_DIR = os.path.join(REPO, "Assets", "Game", "Audio", "Music")
MANIFEST = os.path.join(REPO, "Assets", "Game", "Audio", "audio_manifest.json")

# source filename -> (catalogue name, loops, trigger)
TRACKS = [
    ("26. Battle! (Trainer Battle).mp3", "Music_Battle_Trainer", True,
     "Trainer battle loop; BattleStartedEvent with Kind=Trainer."),
    ("15. Battle! (Wild Pokémon).mp3", "Music_Battle_Wild", True,
     "Wild encounter battle loop; BattleStartedEvent with Kind=Wild."),
    # Two different pieces for two different moments, and they were briefly the same one.
    #
    # "Music_Opening_Introduction" is the PROLOGUE — Linden talking over black before the game
    # has a player in it — and its name has always meant that (EpisodeRunner.OpeningTrack reads
    # it). The title screen is a separate moment and wants the attract piece, so it gets its own
    # clip rather than borrowing the professor's.
    ("05. Introduction.mp3", "Music_Opening_Introduction", True,
     "The prologue: Linden's monologue over black. EpisodeRunner.OpeningTrack."),
    ("01. Opening Movie (Pokémon Diamond & Pokémon Pearl).mp3", "Music_Title", True,
     "The title screen. MainMenuPresenter._titleTrack."),
    ("27. Victory! (Trainer Battle).mp3", "Music_Victory_Fanfare", False,
     "Played once when the player wins; not a loop."),
]


def measure(path):
    done = subprocess.run(["ffmpeg", "-i", path, "-af", "volumedetect", "-f", "null", "-"],
                          capture_output=True, text=True, encoding="utf-8", errors="ignore")
    err = done.stderr or ""
    peak = re.search(r"max_volume: (-?[\d.]+) dB", err)
    mean = re.search(r"mean_volume: (-?[\d.]+) dB", err)
    return (float(peak.group(1)) if peak else 0.0,
            float(mean.group(1)) if mean else -20.0)


def probe(path):
    done = subprocess.run(
        ["ffprobe", "-v", "quiet", "-show_entries",
         "format=duration:stream=sample_rate,channels", "-of", "json", path],
        capture_output=True, text=True)
    try:
        data = json.loads(done.stdout or "{}")
        stream = (data.get("streams") or [{}])[0]
        return (round(float(data["format"]["duration"]), 4),
                int(stream.get("sample_rate", 44100)),
                int(stream.get("channels", 2)))
    except Exception:
        return 0.0, 44100, 2


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    jobs, missing = [], []
    for source, name, loop, trigger in TRACKS:
        path = os.path.join(DOWNLOADS, source)
        (jobs if os.path.isfile(path) else missing).append((path, source, name, loop, trigger))

    for path, source, name, loop, trigger in missing:
        print("MISSING: %s" % source)
    if args.dry_run:
        for path, source, name, loop, trigger in jobs:
            print("  %-56s -> %s.mp3  (loop=%s)" % (source, name, loop))
        return 0
    if not jobs:
        print("Nothing to import.")
        return 1

    os.makedirs(OUT_DIR, exist_ok=True)
    written = []
    for path, source, name, loop, trigger in jobs:
        out = os.path.join(OUT_DIR, name + ".mp3")
        peak, _ = measure(path)
        gain = -1.0 - peak
        # Re-encoded rather than copied, because the gain has to be applied. 192k CBR keeps a
        # full-band mix clean; the browser re-compresses on top of this either way.
        subprocess.run(["ffmpeg", "-y", "-v", "error", "-i", path,
                        "-af", "volume=%.2fdB" % gain,
                        "-c:a", "libmp3lame", "-b:a", "192k", "-ar", "44100", out], check=True)

        duration, rate, channels = probe(out)
        new_peak, new_mean = measure(out)
        written.append({
            "name": name,
            "path": "Assets/Game/Audio/Music/%s.mp3" % name,
            "category": "Music",
            "loop": loop,
            "duration": duration,
            "channels": channels,
            "sample_rate": rate,
            "bit_depth": 16,
            "peak_dbfs": round(new_peak, 2),
            "rms_dbfs": round(new_mean, 2),
            "bytes": os.path.getsize(out),
            "loop_step_ratio": 0.0 if loop else None,
            "trigger": trigger,
        })

    manifest = json.load(io.open(MANIFEST, encoding="utf-8"))
    by_name = {entry["name"]: i for i, entry in enumerate(manifest["clips"])}
    stale = []
    for entry in written:
        index = by_name.get(entry["name"])
        if index is None:
            manifest["clips"].append(entry)
            continue
        # The generated .wav it replaces is now orphaned; report it so it can be deleted
        # deliberately rather than left to rot in the folder.
        old = manifest["clips"][index].get("path", "")
        if old and old != entry["path"]:
            stale.append(old)
        manifest["clips"][index] = entry

    manifest["clips"].sort(key=lambda e: e["name"])
    json.dump(manifest, io.open(MANIFEST, "w", encoding="utf-8", newline="\n"),
              ensure_ascii=False, indent=2)

    total = sum(e["bytes"] for e in written)
    print("wrote %d track(s), %.1f MB" % (len(written), total / 1048576.0))
    for entry in written:
        print("  %-30s %6.1fs  loop=%s" % (entry["name"], entry["duration"], entry["loop"]))
    if stale:
        print("\nSuperseded files, safe to delete once the catalogue is rebuilt:")
        for path in stale:
            print("  %s" % path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
