// GENERATED by Tools regeneration from Assets/StreamingAssets/pokelab/species.json
// intersected with Assets/Game/Art/Sprites/Creatures/sprite_manifest.json.
//
// The pool is the 53 species that HAVE ARTWORK, not the 721 in the dex. A gacha that can
// hand out a creature the client cannot draw is a gacha that hands out a blank rectangle,
// and the manifest is the only honest list of what can be shown.
//
// speciesId is the GAME id (SliceRoster space), the same id CreatureFactory and the staged
// encounters use -- NOT the national dex number. They collide: game 25 is Rattata, dex 25 is
// Pikachu. Getting this wrong produces a plausible wrong creature rather than an error, which
// is why it is said here as well as in the manifest.
//
// The tier is derived from the base stat total once, here, rather than computed per roll:
// the odds are a published property of the game and must not drift with a stat rebalance
// nobody remembered was load-bearing.

export type Rarity = "common" | "uncommon" | "rare" | "epic" | "legendary";

export const RARITY_ORDER: Rarity[] = ["common", "uncommon", "rare", "epic", "legendary"];

/** Relative weight of each TIER as a whole. Within a tier every species is equally likely. */
export const TIER_WEIGHT: Record<Rarity, number> = {
  common: 55,
  uncommon: 27,
  rare: 12,
  epic: 4.5,
  legendary: 1.5
};

export interface PoolEntry {
  speciesId: number;
  name: string;
  nameKo: string;
  bst: number;
  rarity: Rarity;
}

export const POOL: PoolEntry[] = [
  { speciesId: 1, name: "Bulbasaur", nameKo: "이상해씨", bst: 318, rarity: "common" },
  { speciesId: 5, name: "Charmander", nameKo: "파이리", bst: 309, rarity: "common" },
  { speciesId: 10, name: "Squirtle", nameKo: "꼬부기", bst: 314, rarity: "common" },
  { speciesId: 14, name: "Caterpie", nameKo: "캐터피", bst: 195, rarity: "common" },
  { speciesId: 15, name: "Metapod", nameKo: "단데기", bst: 205, rarity: "common" },
  { speciesId: 17, name: "Weedle", nameKo: "뿔충이", bst: 195, rarity: "common" },
  { speciesId: 18, name: "Kakuna", nameKo: "딱충이", bst: 205, rarity: "common" },
  { speciesId: 21, name: "Pidgey", nameKo: "구구", bst: 251, rarity: "common" },
  { speciesId: 25, name: "Rattata", nameKo: "꼬렛", bst: 253, rarity: "common" },
  { speciesId: 27, name: "Spearow", nameKo: "깨비참", bst: 262, rarity: "common" },
  { speciesId: 29, name: "Ekans", nameKo: "아보", bst: 288, rarity: "common" },
  { speciesId: 33, name: "Sandshrew", nameKo: "모래두지", bst: 300, rarity: "common" },
  { speciesId: 47, name: "Zubat", nameKo: "주뱃", bst: 245, rarity: "common" },
  { speciesId: 52, name: "Paras", nameKo: "파라스", bst: 285, rarity: "common" },
  { speciesId: 54, name: "Venonat", nameKo: "콘팡", bst: 305, rarity: "common" },
  { speciesId: 56, name: "Diglett", nameKo: "디그다", bst: 265, rarity: "common" },
  { speciesId: 62, name: "Mankey", nameKo: "망키", bst: 305, rarity: "common" },
  { speciesId: 66, name: "Poliwag", nameKo: "발챙이", bst: 300, rarity: "common" },
  { speciesId: 69, name: "Abra", nameKo: "캐이시", bst: 310, rarity: "common" },
  { speciesId: 73, name: "Machop", nameKo: "알통몬", bst: 305, rarity: "common" },
  { speciesId: 76, name: "Bellsprout", nameKo: "모다피", bst: 300, rarity: "common" },
  { speciesId: 81, name: "Geodude", nameKo: "꼬마돌", bst: 300, rarity: "common" },
  { speciesId: 86, name: "Slowpoke", nameKo: "야돈", bst: 315, rarity: "common" },
  { speciesId: 100, name: "Gastly", nameKo: "고오스", bst: 310, rarity: "common" },
  { speciesId: 126, name: "Horsea", nameKo: "쏘드라", bst: 295, rarity: "common" },
  { speciesId: 140, name: "Magikarp", nameKo: "잉어킹", bst: 200, rarity: "common" },
  { speciesId: 16, name: "Butterfree", nameKo: "버터플", bst: 395, rarity: "uncommon" },
  { speciesId: 19, name: "Beedrill", nameKo: "독침붕", bst: 395, rarity: "uncommon" },
  { speciesId: 31, name: "Pikachu", nameKo: "피카츄", bst: 320, rarity: "uncommon" },
  { speciesId: 41, name: "Clefairy", nameKo: "삐삐", bst: 323, rarity: "uncommon" },
  { speciesId: 49, name: "Oddish", nameKo: "뚜벅쵸", bst: 320, rarity: "uncommon" },
  { speciesId: 50, name: "Gloom", nameKo: "냄새꼬", bst: 395, rarity: "uncommon" },
  { speciesId: 60, name: "Psyduck", nameKo: "고라파덕", bst: 320, rarity: "uncommon" },
  { speciesId: 64, name: "Growlithe", nameKo: "가디", bst: 350, rarity: "uncommon" },
  { speciesId: 67, name: "Poliwhirl", nameKo: "슈륙챙이", bst: 385, rarity: "uncommon" },
  { speciesId: 82, name: "Graveler", nameKo: "데구리", bst: 390, rarity: "uncommon" },
  { speciesId: 107, name: "Krabby", nameKo: "크랩", bst: 325, rarity: "uncommon" },
  { speciesId: 128, name: "Goldeen", nameKo: "콘치", bst: 320, rarity: "uncommon" },
  { speciesId: 130, name: "Staryu", nameKo: "별가사리", bst: 340, rarity: "uncommon" },
  { speciesId: 145, name: "Eevee", nameKo: "이브이", bst: 325, rarity: "uncommon" },
  { speciesId: 2, name: "Ivysaur", nameKo: "이상해풀", bst: 405, rarity: "rare" },
  { speciesId: 6, name: "Charmeleon", nameKo: "리자드", bst: 405, rarity: "rare" },
  { speciesId: 11, name: "Wartortle", nameKo: "어니부기", bst: 405, rarity: "rare" },
  { speciesId: 23, name: "Pidgeot", nameKo: "피죤투", bst: 479, rarity: "rare" },
  { speciesId: 26, name: "Raticate", nameKo: "레트라", bst: 413, rarity: "rare" },
  { speciesId: 74, name: "Machoke", nameKo: "근육몬", bst: 405, rarity: "rare" },
  { speciesId: 95, name: "Dewgong", nameKo: "쥬레곤", bst: 475, rarity: "rare" },
  { speciesId: 32, name: "Raichu", nameKo: "라이츄", bst: 485, rarity: "epic" },
  { speciesId: 51, name: "Vileplume", nameKo: "라플레시아", bst: 490, rarity: "epic" },
  { speciesId: 83, name: "Golem", nameKo: "딱구리", bst: 495, rarity: "epic" },
  { speciesId: 12, name: "Blastoise", nameKo: "거북왕", bst: 530, rarity: "legendary" },
  { speciesId: 75, name: "Machamp", nameKo: "괴력몬", bst: 505, rarity: "legendary" },
  { speciesId: 102, name: "Gengar", nameKo: "팬텀", bst: 500, rarity: "legendary" },
];

export const BY_RARITY: Record<Rarity, PoolEntry[]> = RARITY_ORDER.reduce((acc, rarity) => {
  acc[rarity] = POOL.filter((entry) => entry.rarity === rarity);
  return acc;
}, {} as Record<Rarity, PoolEntry[]>);

export function rarityRank(rarity: Rarity): number {
  return Math.max(0, RARITY_ORDER.indexOf(rarity));
}
