using System;
using System.Collections.Generic;
using System.IO;
using PokeLab.Overworld;
using Unity.AI.Navigation;
using UnityEngine.AI;
using UnityEditor;
using UnityEngine;

namespace PokeLab.Boot.Editor
{
    /// <summary>
    /// Builds the playable scene from the designed layout.
    ///
    /// The layout is data, not a scene, deliberately: it is generated by a seeded script
    /// and regenerated whenever the design changes, so hand-placing it once would throw
    /// that away. This reads the flattened form produced by
    /// <c>Tools/Level/emit_unity_layout.py</c> and rebuilds the whole thing in one pass.
    ///
    /// The terrain arrives as one continuous surface split into chunks, sampled from the
    /// baked height grid that every object's Y was taken from. It used to arrive as flat
    /// polygonal "decks" held at a constant height, which is why the world looked like
    /// plates laid on top of each other; there is no deck concept in the design and there
    /// is none here now.
    ///
    /// Normals come from the emitter rather than from RecalculateNormals, because each
    /// chunk would otherwise compute a one-sided derivative along its shared edge and
    /// leave a lighting seam on every chunk boundary.
    /// </summary>
    public static class LevelLayoutBuilder
    {
        private const string LayoutDir = "Assets/Game/Data/Levels/";
        private const string RootName = "Level";

        /// <summary>
        /// Which emitted layout belongs to which scene.
        ///
        /// The slice is emitted per scene rather than as one map: the zones already have
        /// different rules -- the town's encounter rate is zero and it has its own
        /// ambience -- and one scene means one height field where the town's building
        /// pads and the route's cliffs fight over the same grid, one lighting rig for
        /// two moods, and everything in both loaded at once.
        /// </summary>
        private static readonly (string Scene, string Layout)[] SceneLayouts =
        {
            ("Overworld", "slice_town_unity.json"),
            ("Town", "slice_town_unity.json"),
            ("Field", "slice_field_unity.json"),
        };

        private static string LayoutFor(string sceneName)
        {
            foreach (var (scene, layout) in SceneLayouts)
                if (string.Equals(scene, sceneName, StringComparison.OrdinalIgnoreCase))
                    return LayoutDir + layout;
            return LayoutDir + "slice_layout_unity.json";
        }

        private const string TerrainMaterial =
            "Assets/Game/Art/Environment/Terrain/Materials/M_Ground_TerrainBlend.mat";
        private const string WaterMaterial =
            "Assets/Game/Shaders/Materials/M_Water_Lake.mat";
        private const string FoliageMaterial =
            "Assets/Game/Art/Environment/Foliage/Materials/M_Env_Foliage.mat";

        [MenuItem("Tools/Poké Lab/Level/Build Slice Layout")]
        public static void Build() => Build(null);

        /// <summary>Builds a named scene's layout, or the one matching the open scene.</summary>
        public static void Build(string sceneName)
        {
            var open = UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene().name;
            var layoutPath = LayoutFor(string.IsNullOrEmpty(sceneName) ? open : sceneName);

            if (!File.Exists(layoutPath))
            {
                Debug.LogError($"[Level] {layoutPath} not found. Run Tools/Level/emit_unity_layout.py first.");
                return;
            }

            var layout = JsonUtility.FromJson<Layout>(File.ReadAllText(layoutPath));
            if (layout == null || layout.ground == null || layout.ground.Length == 0)
            {
                Debug.LogError("[Level] Layout parsed but carried no ground. Expected " +
                               "schema pokelab-level-unity/2 — re-run the emitter.");
                return;
            }

            var existing = GameObject.Find(RootName);
            if (existing != null) UnityEngine.Object.DestroyImmediate(existing);

            var root = new GameObject(RootName);
            var parents = new Dictionary<string, Transform>();
            var missing = new HashSet<string>();
            var stats = new Stats();

            try
            {
                BuildGround(layout, root.transform, parents);
                BuildWater(layout, root.transform, parents);
                BuildObjects(layout, root.transform, parents, missing);
                BuildFoliage(layout, root.transform, parents, missing, stats);
                BuildTallGrass(layout, root.transform, parents);
                BuildCaveEntrances(layout, root.transform, parents);
                BuildSceneLinks(layout, root.transform, parents);
                BuildPeople(layout, root.transform, parents);
                BuildAnchors(layout, root.transform, parents);
                BuildSpawn(layout, root.transform);
                BuildNavigation(root);
            }
            finally
            {
                EditorUtility.ClearProgressBar();
            }

            if (missing.Count > 0)
            {
                Debug.LogWarning($"[Level] {missing.Count} asset path(s) could not be loaded. " +
                                 "Those entries were skipped:\n  " + string.Join("\n  ", missing));
            }

            // Persist it. The builder runs in memory and nothing was saving the result,
            // so the scene on disk held a camera and an empty spawn marker: pressing Play
            // reloaded from disk and showed nothing at all. It never surfaced because the
            // capture tool builds and renders in the same session, so every review frame
            // was of a level that existed only for as long as the capture took.
            var scene = UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene();
            UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);
            UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);

            Debug.Log(
                $"[Level] Built '{RootName}': {layout.ground.Length} ground chunks " +
                $"({stats.GroundTriangles} tris), {layout.water?.Length ?? 0} water, " +
                $"{layout.objects?.Length ?? 0} objects, {stats.FoliageInstances} foliage " +
                $"instances in {stats.FoliageGroups} instanced group(s), " +
                $"{layout.tallGrass?.Length ?? 0} grass triggers, " +
                $"{layout.caveEntrances?.Length ?? 0} cave entrance(s), " +
                $"{layout.sceneLinks?.Length ?? 0} scene link(s), " +
                $"{layout.npcs?.Length ?? 0} npc(s), {layout.trainers?.Length ?? 0} trainer(s), " +
                $"{layout.ambientAnchors?.Length ?? 0} anchors.");
        }

        private sealed class Stats
        {
            public int GroundTriangles;
            public int FoliageInstances;
            public int FoliageGroups;
        }

        /// <summary>
        /// Bakes navigation over the level that was just built.
        ///
        /// This has to happen here rather than being a one-off in the scene. The terrain
        /// is generated: every regeneration moves the ground, and a bake from before it
        /// covers geometry that no longer exists. The symptom is not subtle but it is
        /// misleading — NavMeshAgent throws "can only be called on an active agent that
        /// has been placed on a NavMesh" once per frame per NPC, which reads as a bug in
        /// the NPC rather than as stale navigation.
        ///
        /// The surface collects by layer so it follows the same Ground/Environment split
        /// the builder already applies, and it is rebuilt rather than added to, so
        /// removing an object removes what it carved.
        /// </summary>
        private static void BuildNavigation(GameObject root)
        {
            var surface = root.GetComponent<NavMeshSurface>();
            if (surface == null) surface = root.AddComponent<NavMeshSurface>();

            surface.collectObjects = CollectObjects.Children;
            surface.useGeometry = NavMeshCollectGeometry.PhysicsColliders;
            var ground = LayerMask.NameToLayer("Ground");
            var environment = LayerMask.NameToLayer("Environment");
            var interactable = LayerMask.NameToLayer("Interactable");
            surface.layerMask = MaskOf(ground) | MaskOf(environment) | MaskOf(interactable);

            // Matched to PlayerLocomotion so what the agents can walk is what the player
            // can walk. A navmesh built to different limits sends NPCs up slopes the
            // player cannot follow them onto.
            surface.overrideVoxelSize = true;
            surface.voxelSize = 0.12f;

            surface.BuildNavMesh();

            // BuildNavMesh leaves the data in memory. Unless it is written out as an
            // asset it is gone the moment the scene reloads, and every agent then reports
            // "not close enough to the NavMesh" — which reads as a placement fault rather
            // than as navigation that was never saved.
            if (surface.navMeshData != null)
            {
                var scene = UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene();
                var dir = "Assets/Game/Data/Navigation";
                if (!AssetDatabase.IsValidFolder(dir))
                    AssetDatabase.CreateFolder("Assets/Game/Data", "Navigation");

                var path = $"{dir}/NavMesh-{(string.IsNullOrEmpty(scene.name) ? "Level" : scene.name)}.asset";
                var existing = AssetDatabase.LoadAssetAtPath<UnityEngine.AI.NavMeshData>(path);
                if (existing != null) AssetDatabase.DeleteAsset(path);
                AssetDatabase.CreateAsset(surface.navMeshData, path);
                AssetDatabase.SaveAssets();
                Debug.Log($"[Level] Navigation baked and saved to {path}.");
            }
            else
            {
                Debug.LogWarning("[Level] Navigation produced no data. Nothing on the " +
                                 "Ground, Environment or Interactable layers was walkable, " +
                                 "so every NPC will stand still.");
            }
        }

        private static int MaskOf(int layer) => layer >= 0 ? 1 << layer : 0;

        // --- terrain ------------------------------------------------------------------

        private static void BuildGround(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            var material = AssetDatabase.LoadAssetAtPath<Material>(TerrainMaterial);
            var parent = ResolveParent(root, parents, "Terrain/Ground");

            foreach (var chunk in layout.ground)
            {
                var mesh = new Mesh { name = chunk.name };
                mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;

                var count = chunk.vertices.Length / 3;
                var verts = new Vector3[count];
                var norms = new Vector3[count];
                var cols = new Color[count];
                var uvs = new Vector2[count];

                for (var i = 0; i < count; i++)
                {
                    verts[i] = new Vector3(chunk.vertices[i * 3],
                                           chunk.vertices[i * 3 + 1],
                                           chunk.vertices[i * 3 + 2]);
                    norms[i] = new Vector3(chunk.normals[i * 3],
                                           chunk.normals[i * 3 + 1],
                                           chunk.normals[i * 3 + 2]);
                    // RGBA are the terrain shader's grass / dirt / sand / rock weights.
                    // The roads live in here rather than as their own meshes, which is
                    // why there is nothing to z-fight along 191 m of road.
                    cols[i] = new Color(chunk.colors[i * 4], chunk.colors[i * 4 + 1],
                                        chunk.colors[i * 4 + 2], chunk.colors[i * 4 + 3]);
                    uvs[i] = new Vector2(chunk.uvs[i * 2], chunk.uvs[i * 2 + 1]);
                }

                mesh.vertices = verts;
                mesh.normals = norms;
                mesh.colors = cols;
                mesh.uv = uvs;
                mesh.triangles = chunk.triangles;
                mesh.RecalculateTangents();
                mesh.RecalculateBounds();

                var go = new GameObject(chunk.name);
                go.transform.SetParent(parent, false);
                go.AddComponent<MeshFilter>().sharedMesh = mesh;
                var renderer = go.AddComponent<MeshRenderer>();
                if (material != null) renderer.sharedMaterial = material;
                go.AddComponent<MeshCollider>().sharedMesh = mesh;

                go.isStatic = true;
                SetLayer(go, "Ground");
            }
        }

        private static void BuildWater(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            var material = AssetDatabase.LoadAssetAtPath<Material>(WaterMaterial);
            var parent = ResolveParent(root, parents, "Terrain/Water");

            foreach (var body in layout.water ?? Array.Empty<WaterSurface>())
            {
                var mesh = new Mesh { name = body.name };
                mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;

                var count = body.vertices.Length / 3;
                var verts = new Vector3[count];
                var uvs = new Vector2[count];
                for (var i = 0; i < count; i++)
                {
                    verts[i] = new Vector3(body.vertices[i * 3],
                                           body.vertices[i * 3 + 1],
                                           body.vertices[i * 3 + 2]);
                    uvs[i] = new Vector2(body.uvs[i * 2], body.uvs[i * 2 + 1]);
                }

                mesh.vertices = verts;
                mesh.uv = uvs;
                mesh.triangles = body.triangles;
                mesh.RecalculateNormals();
                mesh.RecalculateTangents();
                mesh.RecalculateBounds();

                var go = new GameObject(body.name);
                go.transform.SetParent(parent, false);
                go.AddComponent<MeshFilter>().sharedMesh = mesh;
                var renderer = go.AddComponent<MeshRenderer>();
                if (material != null) renderer.sharedMaterial = material;

                // A trigger, not a solid: the surf/fishing triggers read it and the player
                // is stopped by the bank, which is terrain, not by the water itself.
                var collider = go.AddComponent<MeshCollider>();
                collider.sharedMesh = mesh;
                collider.convex = false;

                go.isStatic = true;
                SetLayer(go, "Water");
            }
        }

        // --- scattered detail ------------------------------------------------------------

        private static void BuildFoliage(Layout layout, Transform root,
            Dictionary<string, Transform> parents, HashSet<string> missing, Stats stats)
        {
            if (layout.foliage == null) return;
            var material = AssetDatabase.LoadAssetAtPath<Material>(FoliageMaterial);
            if (material == null)
            {
                missing.Add(FoliageMaterial);
                return;
            }

            foreach (var field in layout.foliage)
            {
                if (field.groups == null || field.groups.Length == 0) continue;

                var host = new GameObject(field.name);
                host.transform.SetParent(
                    ResolveParent(root, parents, string.IsNullOrEmpty(field.parent)
                        ? "Terrain/Foliage" : field.parent), false);
                SetLayer(host, "Environment");
                var renderer = host.AddComponent<InstancedFoliage>();

                foreach (var group in field.groups)
                {
                    var mesh = LoadFirstMesh(group.prefab);
                    if (mesh == null)
                    {
                        missing.Add(group.prefab);
                        continue;
                    }

                    // Five floats per instance: x, y, z, yaw, uniform scale.
                    var stride = 5;
                    var count = group.instances.Length / stride;
                    var transforms = new List<Matrix4x4>(count);
                    for (var i = 0; i < count; i++)
                    {
                        var o = i * stride;
                        transforms.Add(Matrix4x4.TRS(
                            new Vector3(group.instances[o], group.instances[o + 1], group.instances[o + 2]),
                            Quaternion.Euler(0f, group.instances[o + 3], 0f),
                            Vector3.one * group.instances[o + 4]));
                    }

                    renderer.SetGroup(mesh, material, transforms);
                    stats.FoliageInstances += count;
                    stats.FoliageGroups++;
                }
            }
        }

        /// <summary>
        /// Pulls the mesh out of an imported FBX. Instancing needs the mesh and a shared
        /// material, not a prefab: a prefab would drag along its own renderer settings and
        /// there would be nothing to instance.
        /// </summary>
        private static Mesh LoadFirstMesh(string path)
        {
            foreach (var asset in AssetDatabase.LoadAllAssetsAtPath(path))
                if (asset is Mesh mesh) return mesh;
            return null;
        }

        private static void BuildTallGrass(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var patch in layout.tallGrass ?? Array.Empty<GrassTrigger>())
            {
                var go = new GameObject(patch.name);
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/TallGrass"), false);
                go.transform.localPosition = ToVector(patch.centre);

                var box = go.AddComponent<BoxCollider>();
                box.size = ToVector(patch.triggerSize, Vector3.one);
                box.isTrigger = true;

                go.AddComponent<PokeLab.Overworld.TallGrassPatch>();
                SetLayer(go, "ZoneTrigger");
            }
        }

        private static void BuildCaveEntrances(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var entrance in layout.caveEntrances ?? Array.Empty<CaveEntrance>())
            {
                // Caves are their own scenes, so the overworld carries only the doorway.
                // Nothing inside a cave is emitted into this build at all: the height grid
                // describes the mountain's outside, so an interior prop placed here would
                // sit on the summit above the chamber it belongs to.
                var go = new GameObject($"CaveEntrance_{entrance.name}");
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/Transitions"), false);
                go.transform.localPosition = ToVector(entrance.position);
                go.transform.localEulerAngles = new Vector3(0f, entrance.facingYaw, 0f);

                var box = go.AddComponent<BoxCollider>();
                box.size = ToVector(entrance.size, Vector3.one);
                box.center = new Vector3(0f, box.size.y * 0.5f, 0f);
                box.isTrigger = true;

                SetLayer(go, "ZoneTrigger");
            }
        }

        /// <summary>
        /// The doors out of this scene. Same machinery as a cave mouth, because they are
        /// the same thing: a volume you walk into that loads somewhere else.
        /// </summary>
        private static void BuildSceneLinks(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var link in layout.sceneLinks ?? Array.Empty<SceneLink>())
            {
                var go = new GameObject($"To_{link.scene}");
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/Transitions"), false);
                go.transform.localPosition = ToVector(link.position);
                go.transform.localEulerAngles = new Vector3(0f, link.facingYaw, 0f);

                var box = go.AddComponent<BoxCollider>();
                box.size = ToVector(link.size, Vector3.one);
                box.center = new Vector3(0f, box.size.y * 0.5f, 0f);
                box.isTrigger = true;

                go.AddComponent<LevelTransition>().Configure(link.scene, link.arrivalSpawn);
                SetLayer(go, "ZoneTrigger");

                // Where the player is put down arriving from the other side. Resolved by
                // name across the load, so neither scene holds a reference into the other.
                var arrival = new GameObject(link.arrivalSpawn);
                arrival.transform.SetParent(ResolveParent(root, parents, "Gameplay/Arrivals"), false);
                arrival.transform.localPosition =
                    ToVector(link.position) + Quaternion.Euler(0f, link.facingYaw, 0f) * Vector3.back * 2.5f;
            }
        }

        /// <summary>
        /// Stands the authored residents and trainers up in the world.
        ///
        /// Nothing was doing this. Six NPCs and four trainers are authored in the layout
        /// with positions, schedules and sight cones, the sprite pipeline has finished
        /// sixteen characters, and the scene came up empty every time — two separate
        /// workstreams reported it independently as "the level has no people".
        ///
        /// They are built as bare transforms carrying their controller. The visual is a
        /// billboarded sprite bound at runtime from the person manifest, which is why
        /// there is no prefab to instantiate: a prefab per character would be sixteen
        /// assets that only differ by which sheet they name.
        /// </summary>
        private static void BuildPeople(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var npc in layout.npcs ?? Array.Empty<NpcRecord>())
            {
                var go = new GameObject(npc.name);
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/Npcs"), false);
                go.transform.localPosition = ToVector(npc.position);
                go.transform.localEulerAngles = ToVector(npc.rotation);

                var body = go.AddComponent<CapsuleCollider>();
                body.height = 1.7f;
                body.radius = 0.28f;
                body.center = new Vector3(0f, 0.85f, 0f);

                var controller = go.AddComponent<NpcController>();
                controller.Configure(npc.npcId, npc.displayName,
                                     ToSchedule(npc.schedule, go.transform));
                SetLayer(go, "Interactable");
                TrySetTag(go, "Interactable");
            }

            foreach (var trainer in layout.trainers ?? Array.Empty<TrainerRecord>())
            {
                var go = new GameObject(trainer.name);
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/Trainers"), false);
                go.transform.localPosition = ToVector(trainer.position);
                go.transform.localEulerAngles = ToVector(trainer.rotation);

                var body = go.AddComponent<CapsuleCollider>();
                body.height = 1.7f;
                body.radius = 0.28f;
                body.center = new Vector3(0f, 0.85f, 0f);

                go.AddComponent<TrainerController>()
                  .Configure(trainer.trainerId, trainer.sightRange, trainer.sightHalfAngle);
                SetLayer(go, "Interactable");
                TrySetTag(go, "Interactable");
            }
        }

        /// <summary>
        /// Turns the authored schedule into entries the controller can use.
        ///
        /// Each waypoint becomes a real Transform, because that is what
        /// NpcScheduleEntry holds — an NPC's destination is a thing in the world that can
        /// be moved, not a coordinate baked into a component. They are parented to the
        /// NPC so a rebuild takes its markers with it, and placed in world space so they
        /// stay put when the NPC walks away from them.
        /// </summary>
        private static List<NpcScheduleEntry> ToSchedule(ScheduleRecord[] records, Transform owner)
        {
            var list = new List<NpcScheduleEntry>();
            var index = 0;
            foreach (var record in records ?? Array.Empty<ScheduleRecord>())
            {
                var marker = new GameObject($"Waypoint_{index:D2}_{record.activity}");
                marker.transform.SetParent(owner, false);
                marker.transform.position = ToVector(record.waypoint, owner.position);

                list.Add(new NpcScheduleEntry
                {
                    StartHour = record.startHour,
                    Activity = ParseActivity(record.activity),
                    Waypoint = marker.transform,
                    WanderRadius = record.wanderRadius,
                });
                index++;
            }
            return list;
        }

        private static NpcActivity ParseActivity(string value) =>
            Enum.TryParse<NpcActivity>(value, true, out var parsed) ? parsed : NpcActivity.Idle;

        // --- props, anchors, spawn -------------------------------------------------------

        private static void BuildObjects(Layout layout, Transform root,
            Dictionary<string, Transform> parents, HashSet<string> missing)
        {
            var objects = layout.objects ?? Array.Empty<Placement>();
            var cache = new Dictionary<string, GameObject>();

            for (var i = 0; i < objects.Length; i++)
            {
                if ((i & 127) == 0 &&
                    EditorUtility.DisplayCancelableProgressBar(
                        "Building level", $"{i} / {objects.Length}", i / (float)objects.Length))
                {
                    Debug.LogWarning("[Level] Build cancelled; the scene is incomplete.");
                    return;
                }

                var entry = objects[i];
                if (string.IsNullOrEmpty(entry.prefab)) continue;

                if (!cache.TryGetValue(entry.prefab, out var prefab))
                {
                    prefab = AssetDatabase.LoadAssetAtPath<GameObject>(entry.prefab);
                    cache[entry.prefab] = prefab;
                }

                if (prefab == null)
                {
                    missing.Add(entry.prefab);
                    continue;
                }

                var instance = (GameObject)PrefabUtility.InstantiatePrefab(
                    prefab, ResolveParent(root, parents, entry.parent));
                if (instance == null) continue;

                instance.name = entry.name;
                instance.transform.localPosition = ToVector(entry.position);
                instance.transform.localEulerAngles = ToVector(entry.rotation);
                instance.transform.localScale = ToVector(entry.scale, Vector3.one);
                instance.isStatic = entry.@static;
                AddCollision(instance, entry.collider);
                if (!string.IsNullOrEmpty(entry.layer)) SetLayer(instance, entry.layer);
                if (!string.IsNullOrEmpty(entry.tag) && entry.tag != "Untagged")
                    TrySetTag(instance, entry.tag);
            }
        }

        /// <summary>
        /// Gives a placed object something to collide with.
        ///
        /// Instantiating an FBX gives renderers and no colliders, and nothing was adding
        /// any: every tree, house, rock and the bridge could be walked straight through,
        /// and the only solid things in the level were the ground mesh and the trigger
        /// volumes. The bridge is the one that bites hardest — the terrain dives into the
        /// stream channel beneath it, so without a deck to stand on the player walks the
        /// route straight into the water.
        ///
        /// Trees get a capsule on the stem rather than a collider around their geometry.
        /// A mesh collider on a broadleaf is a four-metre canopy you cannot walk under,
        /// which would wall off most of the route.
        /// </summary>
        private static void AddCollision(GameObject instance, string kind)
        {
            if (string.IsNullOrEmpty(kind) || kind == "none") return;

            if (kind == "trunk")
            {
                var bounds = LocalBounds(instance);
                if (bounds.size.y <= 0.01f) return;

                var capsule = instance.AddComponent<CapsuleCollider>();
                capsule.direction = 1; // Y
                capsule.height = bounds.size.y;
                capsule.center = new Vector3(0f, bounds.min.y + bounds.size.y * 0.5f, 0f);
                // A fraction of the canopy, because the canopy is what the bounding box
                // measures and the trunk is what you walk into.
                capsule.radius = Mathf.Max(0.18f,
                    Mathf.Min(bounds.size.x, bounds.size.z) * 0.13f);
                return;
            }

            foreach (var filter in instance.GetComponentsInChildren<MeshFilter>(true))
            {
                if (filter.sharedMesh == null) continue;
                var collider = filter.gameObject.AddComponent<MeshCollider>();
                collider.sharedMesh = filter.sharedMesh;
                collider.convex = false;   // static geometry; concave is free here
            }
        }

        /// <summary>Bounds of every renderer, in the instance's own space.</summary>
        private static Bounds LocalBounds(GameObject instance)
        {
            var renderers = instance.GetComponentsInChildren<Renderer>(true);
            if (renderers.Length == 0) return new Bounds(Vector3.zero, Vector3.zero);

            var toLocal = instance.transform.worldToLocalMatrix;
            var bounds = new Bounds(
                toLocal.MultiplyPoint3x4(renderers[0].bounds.center), Vector3.zero);
            foreach (var renderer in renderers)
            {
                var b = renderer.bounds;
                foreach (var corner in Corners(b))
                    bounds.Encapsulate(toLocal.MultiplyPoint3x4(corner));
            }
            return bounds;
        }

        private static IEnumerable<Vector3> Corners(Bounds b)
        {
            var min = b.min;
            var max = b.max;
            yield return new Vector3(min.x, min.y, min.z);
            yield return new Vector3(max.x, min.y, min.z);
            yield return new Vector3(min.x, min.y, max.z);
            yield return new Vector3(max.x, min.y, max.z);
            yield return new Vector3(min.x, max.y, min.z);
            yield return new Vector3(max.x, max.y, min.z);
            yield return new Vector3(min.x, max.y, max.z);
            yield return new Vector3(max.x, max.y, max.z);
        }

        private static void BuildAnchors(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var anchor in layout.ambientAnchors ?? Array.Empty<Anchor>())
            {
                // Anchors are empties. The VFX and audio directors resolve them by name and
                // attach their own emitters, so placing a live effect here would double up.
                var go = new GameObject($"Anchor_{anchor.type}_{anchor.name}");
                go.transform.SetParent(ResolveParent(root, parents, "Ambient"), false);
                go.transform.localPosition = ToVector(anchor.position);
            }
        }

        private static void BuildSpawn(Layout layout, Transform root)
        {
            var spawn = new GameObject("PlayerSpawn");
            spawn.transform.SetParent(root, false);
            spawn.transform.localPosition = ToVector(layout.playerSpawn);
        }

        // --- helpers ---------------------------------------------------------------------

        private static Transform ResolveParent(Transform root,
            Dictionary<string, Transform> parents, string path)
        {
            if (string.IsNullOrEmpty(path)) return root;
            if (parents.TryGetValue(path, out var found)) return found;

            var current = root;
            var accumulated = "";
            foreach (var part in path.Split('/'))
            {
                if (string.IsNullOrEmpty(part)) continue;
                accumulated = string.IsNullOrEmpty(accumulated) ? part : accumulated + "/" + part;
                if (!parents.TryGetValue(accumulated, out var next))
                {
                    next = new GameObject(part).transform;
                    next.SetParent(current, false);
                    parents[accumulated] = next;
                }
                current = next;
            }
            return current;
        }

        private static void SetLayer(GameObject go, string layerName)
        {
            var layer = LayerMask.NameToLayer(layerName);
            if (layer < 0) return;
            foreach (var t in go.GetComponentsInChildren<Transform>(true)) t.gameObject.layer = layer;
        }

        private static void TrySetTag(GameObject go, string tag)
        {
            try { go.tag = tag; }
            catch (UnityException) { /* Undeclared tags are not worth failing a build over. */ }
        }

        private static Vector3 ToVector(float[] v, Vector3 fallback = default) =>
            v != null && v.Length >= 3 ? new Vector3(v[0], v[1], v[2]) : fallback;

        // --- serialized shapes, matching emit_unity_layout.py ------------------------------

        [Serializable]
        private sealed class Layout
        {
            public string schema;
            public GroundChunk[] ground;
            public WaterSurface[] water;
            public FoliageField[] foliage;
            public Placement[] objects;
            public Anchor[] ambientAnchors;
            public GrassTrigger[] tallGrass;
            public CaveEntrance[] caveEntrances;
            public SceneLink[] sceneLinks;
            public NpcRecord[] npcs;
            public TrainerRecord[] trainers;
            public float[] playerSpawn;
            public float cameraYaw;
            public float cameraPitch;
            public float cameraDistance;
            public float cameraFov;
        }

        [Serializable]
        private sealed class GroundChunk
        {
            public string name;
            public float[] vertices;
            public float[] normals;
            public float[] colors;
            public float[] uvs;
            public int[] triangles;
        }

        [Serializable]
        private sealed class WaterSurface
        {
            public string name;
            public string kind;
            public float surfaceY;
            public float[] vertices;
            public float[] uvs;
            public int[] triangles;
        }

        [Serializable]
        private sealed class FoliageField
        {
            public string name;
            public string kind;
            public string parent;
            public bool generatesEncounters;
            public FoliageGroup[] groups;
        }

        [Serializable]
        private sealed class FoliageGroup
        {
            public string prefab;
            public float[] instances;
        }

        [Serializable]
        private sealed class GrassTrigger
        {
            public string name;
            public float[] centre;
            public float[] triggerSize;
            public int clumpCount;
            public bool generatesEncounters;
        }

        [Serializable]
        private sealed class CaveEntrance
        {
            public string name;
            public string scene;
            public float[] position;
            public float facingYaw;
            public float[] size;
        }

        [Serializable]
        private sealed class NpcRecord
        {
            public string name;
            public string npcId;
            public string displayName;
            public float[] position;
            public float[] rotation;
            public ScheduleRecord[] schedule;
        }

        [Serializable]
        private sealed class ScheduleRecord
        {
            public float startHour;
            public string activity;
            public float[] waypoint;
            public float wanderRadius;
        }

        [Serializable]
        private sealed class TrainerRecord
        {
            public string name;
            public string trainerId;
            public float[] position;
            public float[] rotation;
            public float sightRange;
            public float sightHalfAngle;
        }

        [Serializable]
        private sealed class SceneLink
        {
            public string name;
            public string scene;
            public string arrivalSpawn;
            public float[] position;
            public float facingYaw;
            public float[] size;
        }

        [Serializable]
        private sealed class Placement
        {
            public string prefab;
            public string name;
            public string parent;
            public float[] position;
            public float[] rotation;
            public float[] scale;
            public string layer;
            public string tag;
            public string collider;
            public bool @static;
        }

        [Serializable]
        private sealed class Anchor
        {
            public string name;
            public string type;
            public float[] position;
        }
    }
}
