using System;
using System.Collections.Generic;
using System.IO;
using PokeLab.Overworld;
using PokeLab.Overworld.People;
using PokeLab.Overworld.World;
using Unity.AI.Navigation;
using UnityEngine.AI;
using UnityEditor;
using UnityEngine;

namespace PokeLab.Boot.Editor
{
    /// <summary>
    /// Builds the playable scene from the designed layout.
    ///
    /// The layout is data, not a scene, deliberately: it is generated by a seeded script
    /// and regenerated whenever the design changes, so hand-placing it once would throw
    /// that away. This reads the flattened form produced by
    /// <c>Tools/Level/emit_unity_layout.py</c> and rebuilds the whole thing in one pass.
    ///
    /// The terrain arrives as one continuous surface split into chunks, sampled from the
    /// baked height grid that every object's Y was taken from. It used to arrive as flat
    /// polygonal "decks" held at a constant height, which is why the world looked like
    /// plates laid on top of each other; there is no deck concept in the design and there
    /// is none here now.
    ///
    /// Normals come from the emitter rather than from RecalculateNormals, because each
    /// chunk would otherwise compute a one-sided derivative along its shared edge and
    /// leave a lighting seam on every chunk boundary.
    /// </summary>
    public static class LevelLayoutBuilder
    {
        private const string LayoutDir = "Assets/Game/Data/Levels/";
        private const string RootName = "Level";

        /// <summary>
        /// Which emitted layout belongs to which scene.
        ///
        /// The slice is emitted per scene rather than as one map: the zones already have
        /// different rules -- the town's encounter rate is zero and it has its own
        /// ambience -- and one scene means one height field where the town's building
        /// pads and the route's cliffs fight over the same grid, one lighting rig for
        /// two moods, and everything in both loaded at once.
        /// </summary>
        private static readonly (string Scene, string Layout)[] SceneLayouts =
        {
            ("Overworld", "slice_town_unity.json"),
            ("Town", "slice_town_unity.json"),
            ("Field", "slice_field_unity.json"),
        };

        private static string LayoutFor(string sceneName)
        {
            foreach (var (scene, layout) in SceneLayouts)
                if (string.Equals(scene, sceneName, StringComparison.OrdinalIgnoreCase))
                    return LayoutDir + layout;
            return LayoutDir + "slice_layout_unity.json";
        }

        private const string TerrainMaterial =
            "Assets/Game/Art/Environment/Terrain/Materials/M_Ground_TerrainBlend.mat";
        private const string WaterMaterial =
            "Assets/Game/Shaders/Materials/M_Water_Lake.mat";
        private const string FoliageMaterial =
            "Assets/Game/Art/Environment/Foliage/Materials/M_Env_Foliage.mat";

        [MenuItem("Tools/Poké Lab/Level/Build Slice Layout")]
        public static void Build() => Build(null);

        /// <summary>Builds a named scene's layout, or the one matching the open scene.</summary>
        public static void Build(string sceneName)
        {
            var open = UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene().name;
            var layoutPath = LayoutFor(string.IsNullOrEmpty(sceneName) ? open : sceneName);

            if (!File.Exists(layoutPath))
            {
                Debug.LogError($"[Level] {layoutPath} not found. Run Tools/Level/emit_unity_layout.py first.");
                return;
            }

            var layout = JsonUtility.FromJson<Layout>(File.ReadAllText(layoutPath));
            if (layout == null || layout.ground == null || layout.ground.Length == 0)
            {
                Debug.LogError("[Level] Layout parsed but carried no ground. Expected " +
                               "schema pokelab-level-unity/2 — re-run the emitter.");
                return;
            }

            var existing = GameObject.Find(RootName);
            if (existing != null) UnityEngine.Object.DestroyImmediate(existing);

            var root = new GameObject(RootName);
            var parents = new Dictionary<string, Transform>();
            var missing = new HashSet<string>();
            var stats = new Stats();

            try
            {
                BuildGround(layout, root.transform, parents);
                BuildWater(layout, root.transform, parents);
                BuildObjects(layout, root.transform, parents, missing);
                BuildFoliage(layout, root.transform, parents, missing, stats);
                BuildTallGrass(layout, root.transform, parents);
                BuildCaveEntrances(layout, root.transform, parents);
                BuildBarriers(layout, root.transform, parents);
                BuildSceneLinks(layout, root.transform, parents);
                BuildPeople(layout, root.transform, parents);
                BuildAnchors(layout, root.transform, parents);
                BuildSpawn(layout, root.transform);
                BuildCast(root.transform, parents);
                BuildNavigation(root);
            }
            finally
            {
                EditorUtility.ClearProgressBar();
            }

            if (missing.Count > 0)
            {
                Debug.LogWarning($"[Level] {missing.Count} asset path(s) could not be loaded. " +
                                 "Those entries were skipped:\n  " + string.Join("\n  ", missing));
            }

            // Persist it. The builder runs in memory and nothing was saving the result,
            // so the scene on disk held a camera and an empty spawn marker: pressing Play
            // reloaded from disk and showed nothing at all. It never surfaced because the
            // capture tool builds and renders in the same session, so every review frame
            // was of a level that existed only for as long as the capture took.
            var scene = UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene();
            UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);
            UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);

            Debug.Log(
                $"[Level] Built '{RootName}': {layout.ground.Length} ground chunks " +
                $"({stats.GroundTriangles} tris), {layout.water?.Length ?? 0} water, " +
                $"{layout.objects?.Length ?? 0} objects, {stats.FoliageInstances} foliage " +
                $"instances in {stats.FoliageGroups} instanced group(s), " +
                $"{layout.tallGrass?.Length ?? 0} grass triggers, " +
                $"{layout.caveEntrances?.Length ?? 0} cave entrance(s), " +
                $"{layout.barrierVolumes?.Length ?? 0} barrier(s), " +
                $"{layout.sceneLinks?.Length ?? 0} scene link(s), " +
                $"{layout.npcs?.Length ?? 0} npc(s), {layout.trainers?.Length ?? 0} trainer(s), " +
                $"{layout.ambientAnchors?.Length ?? 0} anchors.");
        }

        private sealed class Stats
        {
            public int GroundTriangles;
            public int FoliageInstances;
            public int FoliageGroups;
        }

        /// <summary>
        /// Bakes navigation over the level that was just built.
        ///
        /// This has to happen here rather than being a one-off in the scene. The terrain
        /// is generated: every regeneration moves the ground, and a bake from before it
        /// covers geometry that no longer exists. The symptom is not subtle but it is
        /// misleading — NavMeshAgent throws "can only be called on an active agent that
        /// has been placed on a NavMesh" once per frame per NPC, which reads as a bug in
        /// the NPC rather than as stale navigation.
        ///
        /// The surface collects by layer so it follows the same Ground/Environment split
        /// the builder already applies, and it is rebuilt rather than added to, so
        /// removing an object removes what it carved.
        /// </summary>
        private static void BuildNavigation(GameObject root)
        {
            var surface = root.GetComponent<NavMeshSurface>();
            if (surface == null) surface = root.AddComponent<NavMeshSurface>();

            surface.collectObjects = CollectObjects.Children;
            surface.useGeometry = NavMeshCollectGeometry.PhysicsColliders;
            var ground = LayerMask.NameToLayer("Ground");
            var environment = LayerMask.NameToLayer("Environment");
            var interactable = LayerMask.NameToLayer("Interactable");
            surface.layerMask = MaskOf(ground) | MaskOf(environment) | MaskOf(interactable);

            // A bake over no layers succeeds and produces nothing, so say so here. Every
            // agent then fails to spawn, and the error it raises names the agent rather
            // than the mask that excluded the entire world.
            if (surface.layerMask == 0)
            {
                Debug.LogError("[Level] None of the navmesh layers (Ground, Environment, " +
                               "Interactable) exist, so the bake has nothing to walk on. " +
                               "Every NPC will report 'not close enough to the NavMesh'.");
            }

            // Matched to PlayerLocomotion so what the agents can walk is what the player
            // can walk. A navmesh built to different limits sends NPCs up slopes the
            // player cannot follow them onto.
            surface.overrideVoxelSize = true;
            surface.voxelSize = 0.12f;

            surface.BuildNavMesh();

            // BuildNavMesh leaves the data in memory. Unless it is written out as an
            // asset it is gone the moment the scene reloads, and every agent then reports
            // "not close enough to the NavMesh" — which reads as a placement fault rather
            // than as navigation that was never saved.
            if (surface.navMeshData != null)
            {
                var scene = UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene();
                var dir = "Assets/Game/Data/Navigation";
                if (!AssetDatabase.IsValidFolder(dir))
                    AssetDatabase.CreateFolder("Assets/Game/Data", "Navigation");

                var path = $"{dir}/NavMesh-{(string.IsNullOrEmpty(scene.name) ? "Level" : scene.name)}.asset";
                var existing = AssetDatabase.LoadAssetAtPath<UnityEngine.AI.NavMeshData>(path);
                if (existing != null) AssetDatabase.DeleteAsset(path);
                AssetDatabase.CreateAsset(surface.navMeshData, path);
                AssetDatabase.SaveAssets();
                Debug.Log($"[Level] Navigation baked and saved to {path}.");
            }
            else
            {
                Debug.LogWarning("[Level] Navigation produced no data. Nothing on the " +
                                 "Ground, Environment or Interactable layers was walkable, " +
                                 "so every NPC will stand still.");
            }
        }

        private static int MaskOf(int layer) => layer >= 0 ? 1 << layer : 0;

        // --- terrain ------------------------------------------------------------------

        private static void BuildGround(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            var material = AssetDatabase.LoadAssetAtPath<Material>(TerrainMaterial);
            var parent = ResolveParent(root, parents, "Terrain/Ground");

            foreach (var chunk in layout.ground)
            {
                var mesh = new Mesh { name = chunk.name };
                mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;

                var count = chunk.vertices.Length / 3;
                var verts = new Vector3[count];
                var norms = new Vector3[count];
                var cols = new Color[count];
                var uvs = new Vector2[count];

                for (var i = 0; i < count; i++)
                {
                    verts[i] = new Vector3(chunk.vertices[i * 3],
                                           chunk.vertices[i * 3 + 1],
                                           chunk.vertices[i * 3 + 2]);
                    norms[i] = new Vector3(chunk.normals[i * 3],
                                           chunk.normals[i * 3 + 1],
                                           chunk.normals[i * 3 + 2]);
                    // RGBA are the terrain shader's grass / dirt / sand / rock weights.
                    // The roads live in here rather than as their own meshes, which is
                    // why there is nothing to z-fight along 191 m of road.
                    cols[i] = new Color(chunk.colors[i * 4], chunk.colors[i * 4 + 1],
                                        chunk.colors[i * 4 + 2], chunk.colors[i * 4 + 3]);
                    uvs[i] = new Vector2(chunk.uvs[i * 2], chunk.uvs[i * 2 + 1]);
                }

                mesh.vertices = verts;
                mesh.normals = norms;
                mesh.colors = cols;
                mesh.uv = uvs;
                mesh.triangles = chunk.triangles;
                mesh.RecalculateTangents();
                mesh.RecalculateBounds();

                var go = new GameObject(chunk.name);
                go.transform.SetParent(parent, false);
                go.AddComponent<MeshFilter>().sharedMesh = mesh;
                var renderer = go.AddComponent<MeshRenderer>();
                if (material != null) renderer.sharedMaterial = material;
                go.AddComponent<MeshCollider>().sharedMesh = mesh;

                go.isStatic = true;
                SetLayer(go, "Ground");
            }
        }

        private static void BuildWater(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            var material = AssetDatabase.LoadAssetAtPath<Material>(WaterMaterial);
            var parent = ResolveParent(root, parents, "Terrain/Water");

            foreach (var body in layout.water ?? Array.Empty<WaterSurface>())
            {
                var mesh = new Mesh { name = body.name };
                mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;

                var count = body.vertices.Length / 3;
                var verts = new Vector3[count];
                var uvs = new Vector2[count];
                for (var i = 0; i < count; i++)
                {
                    verts[i] = new Vector3(body.vertices[i * 3],
                                           body.vertices[i * 3 + 1],
                                           body.vertices[i * 3 + 2]);
                    uvs[i] = new Vector2(body.uvs[i * 2], body.uvs[i * 2 + 1]);
                }

                mesh.vertices = verts;
                mesh.uv = uvs;
                mesh.triangles = body.triangles;
                mesh.RecalculateNormals();
                mesh.RecalculateTangents();
                mesh.RecalculateBounds();

                var go = new GameObject(body.name);
                go.transform.SetParent(parent, false);
                go.AddComponent<MeshFilter>().sharedMesh = mesh;
                var renderer = go.AddComponent<MeshRenderer>();
                if (material != null) renderer.sharedMaterial = material;

                // A trigger, not a solid: the surf/fishing triggers read it and the player
                // is stopped by the bank, which is terrain, not by the water itself.
                var collider = go.AddComponent<MeshCollider>();
                collider.sharedMesh = mesh;
                collider.convex = false;

                go.isStatic = true;
                SetLayer(go, "Water");

                BuildShoreline(body, mesh, go.transform);
            }
        }

        /// <summary>
        /// Raises a wall along the waterline that the player cannot walk through.
        ///
        /// The lake used to be open, and a player with no way across simply waded to the
        /// middle of it and fell out of the world. Turning them back after the fact was the
        /// first repair and is the wrong shape: they have already stepped into the lake and
        /// been moved by something they did not do. The series never lets the step happen,
        /// so neither does this.
        ///
        /// The wall is derived from the water mesh's own boundary — the edges belonging to
        /// exactly one triangle — rather than from the shore polygon, because the two are
        /// authored separately and would drift apart. One combined curtain mesh is used
        /// instead of a collider per edge: a lake this size has hundreds of boundary edges,
        /// and hundreds of colliders to stop the player entering water they should not be
        /// in is a poor trade.
        /// </summary>
        private static void BuildShoreline(WaterSurface body, Mesh surface, Transform parent)
        {
            const float WallHeight = 3f;
            const float Skirt = 1.5f;

            // Still water only. A stream is crossed, not kept out of: walling its boundary
            // runs a 3 m barrier along both banks and straight across the bridge deck and
            // the stepping stones, closing the route's only gate. The emitter has to cut
            // holes in the ribbon to work around that, which leaves the water visibly
            // interrupted at exactly the two places the player looks at it closely.
            //
            // The kind field has been on this record since the schema was written and
            // nothing read it.
            if (string.Equals(body.kind, "flowing", StringComparison.OrdinalIgnoreCase))
                return;

            var triangles = surface.triangles;
            var vertices = surface.vertices;

            // An edge shared by two triangles is interior; one used once is the outline.
            var seen = new Dictionary<long, int>(triangles.Length);
            for (var i = 0; i < triangles.Length; i += 3)
            {
                AddEdge(seen, triangles[i], triangles[i + 1]);
                AddEdge(seen, triangles[i + 1], triangles[i + 2]);
                AddEdge(seen, triangles[i + 2], triangles[i]);
            }

            var wallVerts = new List<Vector3>();
            var wallTris = new List<int>();
            foreach (var pair in seen)
            {
                if (pair.Value != 1) continue;
                var a = vertices[(int)(pair.Key >> 32)];
                var b = vertices[(int)(pair.Key & 0xFFFFFFFF)];

                var baseIndex = wallVerts.Count;
                wallVerts.Add(a + Vector3.down * Skirt);
                wallVerts.Add(b + Vector3.down * Skirt);
                wallVerts.Add(a + Vector3.up * WallHeight);
                wallVerts.Add(b + Vector3.up * WallHeight);

                // Both windings, so the curtain stops the player from either side. A
                // one-sided collider lets anything that starts on the wrong side walk out
                // through it, and a cutscene or a warp can put the player on either.
                wallTris.AddRange(new[] { baseIndex, baseIndex + 2, baseIndex + 1,
                                          baseIndex + 2, baseIndex + 3, baseIndex + 1,
                                          baseIndex + 1, baseIndex + 2, baseIndex,
                                          baseIndex + 1, baseIndex + 3, baseIndex + 2 });
            }

            if (wallVerts.Count == 0)
            {
                Debug.LogWarning($"[Level] {body.name} has no boundary edges, so no shoreline " +
                                 "was built and the player can walk straight into it.");
                return;
            }

            var wallMesh = new Mesh { name = body.name + "_Shoreline" };
            wallMesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            wallMesh.SetVertices(wallVerts);
            wallMesh.SetTriangles(wallTris, 0);
            wallMesh.RecalculateBounds();

            var wall = new GameObject(body.name + "_Shoreline");
            wall.transform.SetParent(parent, false);
            // No renderer at all. A wall the player can see is a wall they will test.
            var collider = wall.AddComponent<MeshCollider>();
            collider.sharedMesh = wallMesh;
            collider.convex = false;
            wall.AddComponent<PokeLab.Overworld.WaterEdge>();
            wall.isStatic = true;
            SetLayer(wall, "Environment");
        }

        private static void AddEdge(Dictionary<long, int> seen, int a, int b)
        {
            // Keyed on the ordered pair so the two triangles sharing an edge land on the
            // same key whichever way round each of them wound it.
            var lo = Mathf.Min(a, b);
            var hi = Mathf.Max(a, b);
            var key = ((long)lo << 32) | (uint)hi;
            seen[key] = seen.TryGetValue(key, out var count) ? count + 1 : 1;
        }

        // --- scattered detail ------------------------------------------------------------

        private static void BuildFoliage(Layout layout, Transform root,
            Dictionary<string, Transform> parents, HashSet<string> missing, Stats stats)
        {
            if (layout.foliage == null) return;
            var material = AssetDatabase.LoadAssetAtPath<Material>(FoliageMaterial);
            if (material == null)
            {
                missing.Add(FoliageMaterial);
                return;
            }

            foreach (var field in layout.foliage)
            {
                if (field.groups == null || field.groups.Length == 0) continue;

                var host = new GameObject(field.name);
                host.transform.SetParent(
                    ResolveParent(root, parents, string.IsNullOrEmpty(field.parent)
                        ? "Terrain/Foliage" : field.parent), false);
                SetLayer(host, "Environment");
                var renderer = host.AddComponent<InstancedFoliage>();

                foreach (var group in field.groups)
                {
                    var mesh = LoadFirstMesh(group.prefab);
                    if (mesh == null)
                    {
                        missing.Add(group.prefab);
                        continue;
                    }

                    // Five floats per instance: x, y, z, yaw, uniform scale.
                    var stride = 5;
                    var count = group.instances.Length / stride;
                    var transforms = new List<Matrix4x4>(count);
                    for (var i = 0; i < count; i++)
                    {
                        var o = i * stride;
                        transforms.Add(Matrix4x4.TRS(
                            new Vector3(group.instances[o], group.instances[o + 1], group.instances[o + 2]),
                            Quaternion.Euler(0f, group.instances[o + 3], 0f),
                            Vector3.one * group.instances[o + 4]));
                    }

                    renderer.SetGroup(mesh, material, transforms);
                    stats.FoliageInstances += count;
                    stats.FoliageGroups++;
                }
            }
        }

        /// <summary>
        /// Pulls the mesh out of an imported FBX. Instancing needs the mesh and a shared
        /// material, not a prefab: a prefab would drag along its own renderer settings and
        /// there would be nothing to instance.
        /// </summary>
        private static Mesh LoadFirstMesh(string path)
        {
            foreach (var asset in AssetDatabase.LoadAllAssetsAtPath(path))
                if (asset is Mesh mesh) return mesh;
            return null;
        }

        private static void BuildTallGrass(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var patch in layout.tallGrass ?? Array.Empty<GrassTrigger>())
            {
                var go = new GameObject(patch.name);
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/TallGrass"), false);
                go.transform.localPosition = ToVector(patch.centre);

                var box = go.AddComponent<BoxCollider>();
                box.size = ToVector(patch.triggerSize, Vector3.one);
                box.isTrigger = true;

                go.AddComponent<PokeLab.Overworld.TallGrassPatch>();
                SetLayer(go, "ZoneTrigger");
            }
        }

        private static void BuildCaveEntrances(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var entrance in layout.caveEntrances ?? Array.Empty<CaveEntrance>())
            {
                // Caves are their own scenes, so the overworld carries only the doorway.
                // Nothing inside a cave is emitted into this build at all: the height grid
                // describes the mountain's outside, so an interior prop placed here would
                // sit on the summit above the chamber it belongs to.
                var go = new GameObject($"CaveEntrance_{entrance.name}");
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/Transitions"), false);
                go.transform.localPosition = ToVector(entrance.position);
                go.transform.localEulerAngles = new Vector3(0f, entrance.facingYaw, 0f);

                var box = go.AddComponent<BoxCollider>();
                box.size = ToVector(entrance.size, Vector3.one);
                box.center = new Vector3(0f, box.size.y * 0.5f, 0f);
                box.isTrigger = true;

                // The trigger was the whole of it, so walking into a cave did nothing.
                if (!string.IsNullOrEmpty(entrance.scene))
                    go.AddComponent<LevelTransition>().Configure(entrance.scene, "Spawn_FromOverworld");

                SetLayer(go, "ZoneTrigger");
                BuildCaveBlackout(entrance, go.transform);
            }
        }

        /// <summary>
        /// Fills the cave mouth with black.
        ///
        /// The arch is a real tunnel — the mesh runs out over the lip and back down inside,
        /// so you can see up it — and behind that tunnel is nothing at all, because the
        /// interior is a separate scene and the height grid here describes the outside of the
        /// mountain. Looking into the mouth therefore showed the far wall of the arch and then
        /// the world beyond it, which reads as a prop stuck on a hill rather than as a way in.
        ///
        /// Unlit black rather than a dark material: a lit surface picks up the sun and the
        /// LightingDirector's ambient, and "very dark grey that changes through the day" is
        /// exactly the thing a player reads as a wall they might get past. This is the same
        /// mechanism as the building doors and the town gate.
        /// </summary>
        private static void BuildCaveBlackout(CaveEntrance entrance, Transform mouth)
        {
            var size = ToVector(entrance.size, Vector3.one);

            var go = new GameObject("Blackout");
            go.transform.SetParent(mouth, false);

            // Measured in the editor against the built scene, not derived. The offset is
            // large and negative because Env_Cave_Arch's pivot sits about 1.95 m in front
            // of its own mouth plane -- build_layout.py's cave-shelf comment says so, and it
            // is why cutting the shelf only forward left the arch buried. A blackout placed
            // a polite 0.9 m "into" the opening therefore lands well outside it, in front of
            // the stone, reading as a black disc stuck on the cliff.
            go.transform.localPosition = new Vector3(BlackoutOffset.x,
                                                     size.y * 0.5f,
                                                     BlackoutOffset.z);
            go.transform.localRotation = Quaternion.Euler(0f, 180f, 0f);

            var mesh = new Mesh { name = "CaveBlackout" };
            var halfX = size.x * 0.5f;
            var halfY = size.y * 0.5f;
            mesh.vertices = new[]
            {
                new Vector3(-halfX, -halfY, 0f), new Vector3(halfX, -halfY, 0f),
                new Vector3(-halfX,  halfY, 0f), new Vector3(halfX,  halfY, 0f),
            };
            mesh.uv = new[] { Vector2.zero, Vector2.right, Vector2.up, Vector2.one };
            // Wound both ways. The mouth is approached from outside but a scene link can put
            // the player behind it, and a one-sided plane is invisible from there.
            mesh.triangles = new[] { 0, 2, 1, 2, 3, 1, 1, 2, 0, 1, 3, 2 };
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();

            go.AddComponent<MeshFilter>().sharedMesh = mesh;
            var renderer = go.AddComponent<MeshRenderer>();
            renderer.sharedMaterial = BlackoutMaterial();
            renderer.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            renderer.receiveShadows = false;
        }

        /// <summary>
        /// Where the blackout sits relative to the cave entrance marker, in that marker's
        /// local space. Y is taken from the entrance's own height instead, so a taller mouth
        /// still fills.
        /// </summary>
        private static readonly Vector3 BlackoutOffset = new Vector3(-0.25f, 0f, -2.77f);

        private static Material s_blackout;

        private static Material BlackoutMaterial()
        {
            if (s_blackout != null) return s_blackout;

            var shader = Shader.Find("Universal Render Pipeline/Unlit") ?? Shader.Find("Unlit/Color");
            s_blackout = new Material(shader) { name = "~Blackout" };
            if (s_blackout.HasProperty("_BaseColor")) s_blackout.SetColor("_BaseColor", Color.black);
            if (s_blackout.HasProperty("_Color")) s_blackout.SetColor("_Color", Color.black);
            return s_blackout;
        }

        /// <summary>
        /// The doors out of this scene. Same machinery as a cave mouth, because they are
        /// the same thing: a volume you walk into that loads somewhere else.
        /// </summary>
        /// <summary>
        /// Ground height at a world position, read from the same baked grid the emitter
        /// placed every object with.
        ///
        /// Sampled rather than raycast because the answer has to be the one the emitter
        /// used. A raycast would hit whatever collider happens to be there — a rock, a
        /// building's plinth, the water surface — and put a marker on top of it.
        /// </summary>
        private static bool TrySampleGround(Layout layout, float x, float z, out float y)
        {
            y = 0f;
            var grid = layout.heightGrid;
            if (grid?.heights == null || grid.countX < 2 || grid.countZ < 2 || grid.step <= 0f)
                return false;

            var fx = Mathf.Clamp((x - grid.originX) / grid.step, 0f, grid.countX - 1.001f);
            var fz = Mathf.Clamp((z - grid.originZ) / grid.step, 0f, grid.countZ - 1.001f);
            var ix = Mathf.FloorToInt(fx);
            var iz = Mathf.FloorToInt(fz);
            var tx = fx - ix;
            var tz = fz - iz;

            float At(int cx, int cz)
            {
                var index = cz * grid.countX + cx;
                return index >= 0 && index < grid.heights.Length ? grid.heights[index] : 0f;
            }

            // Bilinear, matching worldgen.BakedField.at -- every object's Y came from this
            // exact interpolation, so a marker placed any other way sits at a different
            // height from the props beside it.
            var h0 = Mathf.Lerp(At(ix, iz), At(ix + 1, iz), tx);
            var h1 = Mathf.Lerp(At(ix, iz + 1), At(ix + 1, iz + 1), tx);
            y = Mathf.Lerp(h0, h1, tz);
            return true;
        }

        private static Vector3 SeatOnGround(Layout layout, Vector3 position)
        {
            if (TrySampleGround(layout, position.x, position.z, out var y))
                position.y = y;
            return position;
        }

        private static void BuildSceneLinks(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var link in layout.sceneLinks ?? Array.Empty<SceneLink>())
            {
                var go = new GameObject($"To_{link.scene}");
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/Transitions"), false);
                go.transform.localPosition = ToVector(link.position);
                go.transform.localEulerAngles = new Vector3(0f, link.facingYaw, 0f);

                var box = go.AddComponent<BoxCollider>();
                box.size = ToVector(link.size, Vector3.one);
                box.center = new Vector3(0f, box.size.y * 0.5f, 0f);
                box.isTrigger = true;

                go.AddComponent<LevelTransition>().Configure(link.scene, link.arrivalSpawn);
                SetLayer(go, "ZoneTrigger");

                // Where the player is put down arriving from the other side. Resolved by
                // name across the load, so neither scene holds a reference into the other.
                //
                // Named for where the traveller came *from*, which is the other end of this
                // link. `link.arrivalSpawn` is the name the destination must host, not this
                // scene — building it here put Spawn_FromTown in Town and Spawn_FromField in
                // Field, so each scene held the marker the other one needed and every
                // transition landed the player at the origin.
                var arrival = new GameObject($"Spawn_From{link.scene}");
                arrival.transform.SetParent(ResolveParent(root, parents, "Gameplay/Arrivals"), false);
                // Seated on the ground, not left at the door's height. The link volume sits
                // at the doorway, and 2.5 m back from a doorway on sloped ground is a
                // different height -- so arriving put the player in the air above the far
                // side and they fell in, which is exactly what a level transition must never
                // look like.
                arrival.transform.localPosition = SeatOnGround(layout,
                    ToVector(link.position) + Quaternion.Euler(0f, link.facingYaw, 0f) * Vector3.back * 2.5f);
            }
        }

        /// <summary>
        /// Stands the authored residents and trainers up in the world.
        ///
        /// Nothing was doing this. Six NPCs and four trainers are authored in the layout
        /// with positions, schedules and sight cones, the sprite pipeline has finished
        /// sixteen characters, and the scene came up empty every time — two separate
        /// workstreams reported it independently as "the level has no people".
        ///
        /// They are built as bare transforms carrying their controller. The visual is a
        /// billboarded sprite bound at runtime from the person manifest, which is why
        /// there is no prefab to instantiate: a prefab per character would be sixteen
        /// assets that only differ by which sheet they name.
        /// </summary>
        private static void BuildPeople(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var npc in layout.npcs ?? Array.Empty<NpcRecord>())
            {
                var go = new GameObject(npc.name);
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/Npcs"), false);
                go.transform.localPosition = ToVector(npc.position);
                go.transform.localEulerAngles = ToVector(npc.rotation);

                var body = go.AddComponent<CapsuleCollider>();
                body.height = 1.7f;
                body.radius = 0.28f;
                body.center = new Vector3(0f, 0.85f, 0f);

                var controller = go.AddComponent<NpcController>();
                controller.Configure(npc.npcId, npc.displayName,
                                     ToSchedule(npc.schedule, go.transform));
                AttachSprite(go, npc.spriteKey, npc.name);
                SetLayer(go, "Interactable");
                TrySetTag(go, "Interactable");
            }

            foreach (var trainer in layout.trainers ?? Array.Empty<TrainerRecord>())
            {
                var go = new GameObject(trainer.name);
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/Trainers"), false);
                go.transform.localPosition = ToVector(trainer.position);
                go.transform.localEulerAngles = ToVector(trainer.rotation);

                var body = go.AddComponent<CapsuleCollider>();
                body.height = 1.7f;
                body.radius = 0.28f;
                body.center = new Vector3(0f, 0.85f, 0f);

                go.AddComponent<TrainerController>()
                  .Configure(trainer.trainerId, trainer.sightRange, trainer.sightHalfAngle);
                AttachSprite(go, trainer.spriteKey, trainer.name);
                SetLayer(go, "Interactable");
                TrySetTag(go, "Interactable");
            }
        }

        /// <summary>
        /// Gives a character their drawn body.
        ///
        /// Without this every NPC and every trainer is a capsule collider with a controller
        /// on it: they walk their schedules, they can be talked to, and nothing is drawn.
        /// The art and its manifest had both existed for some time; nothing read them.
        ///
        /// The key comes from the layout when the layout has one, and otherwise from the
        /// object's own name — <c>NPC_Stallholder</c> becomes "stallholder", which
        /// <see cref="PersonSpriteLibrary"/> aliases onto the drawn shopkeeper. That keeps a
        /// level rebuild from depending on an art rebuild.
        /// </summary>
        private static void AttachSprite(GameObject character, string spriteKey, string objectName)
        {
            var key = spriteKey;
            if (string.IsNullOrEmpty(key) && !string.IsNullOrEmpty(objectName))
            {
                var trimmed = objectName;
                foreach (var prefix in new[] { "NPC_", "Npc_", "Trainer_" })
                    if (trimmed.StartsWith(prefix, StringComparison.Ordinal))
                        trimmed = trimmed.Substring(prefix.Length);
                key = trimmed.ToLowerInvariant();
            }
            if (string.IsNullOrEmpty(key)) return;

            var visual = new GameObject("Visual");
            visual.transform.SetParent(character.transform, false);
            visual.AddComponent<MeshFilter>();
            visual.AddComponent<MeshRenderer>();

            var billboard = visual.AddComponent<PersonBillboard>();
            var so = new SerializedObject(billboard);
            var property = so.FindProperty("_personKey");
            if (property != null)
            {
                property.stringValue = key;
                so.ApplyModifiedPropertiesWithoutUndo();
            }
        }

        /// <summary>
        /// Turns the authored schedule into entries the controller can use.
        ///
        /// Each waypoint becomes a real Transform, because that is what
        /// NpcScheduleEntry holds — an NPC's destination is a thing in the world that can
        /// be moved, not a coordinate baked into a component. They are parented to the
        /// NPC so a rebuild takes its markers with it, and placed in world space so they
        /// stay put when the NPC walks away from them.
        /// </summary>
        private static List<NpcScheduleEntry> ToSchedule(ScheduleRecord[] records, Transform owner)
        {
            var list = new List<NpcScheduleEntry>();
            var index = 0;
            foreach (var record in records ?? Array.Empty<ScheduleRecord>())
            {
                var marker = new GameObject($"Waypoint_{index:D2}_{record.activity}");
                marker.transform.SetParent(owner, false);
                marker.transform.position = ToVector(record.waypoint, owner.position);

                list.Add(new NpcScheduleEntry
                {
                    StartHour = record.startHour,
                    Activity = ParseActivity(record.activity),
                    Waypoint = marker.transform,
                    WanderRadius = record.wanderRadius,
                });
                index++;
            }
            return list;
        }

        private static NpcActivity ParseActivity(string value) =>
            Enum.TryParse<NpcActivity>(value, true, out var parsed) ? parsed : NpcActivity.Idle;

        // --- props, anchors, spawn -------------------------------------------------------

        private static void BuildObjects(Layout layout, Transform root,
            Dictionary<string, Transform> parents, HashSet<string> missing)
        {
            var objects = layout.objects ?? Array.Empty<Placement>();
            var cache = new Dictionary<string, GameObject>();

            for (var i = 0; i < objects.Length; i++)
            {
                if ((i & 127) == 0 &&
                    EditorUtility.DisplayCancelableProgressBar(
                        "Building level", $"{i} / {objects.Length}", i / (float)objects.Length))
                {
                    Debug.LogWarning("[Level] Build cancelled; the scene is incomplete.");
                    return;
                }

                var entry = objects[i];
                if (string.IsNullOrEmpty(entry.prefab)) continue;

                if (!cache.TryGetValue(entry.prefab, out var prefab))
                {
                    prefab = AssetDatabase.LoadAssetAtPath<GameObject>(entry.prefab);
                    cache[entry.prefab] = prefab;
                }

                if (prefab == null)
                {
                    missing.Add(entry.prefab);
                    continue;
                }

                var instance = (GameObject)PrefabUtility.InstantiatePrefab(
                    prefab, ResolveParent(root, parents, entry.parent));
                if (instance == null) continue;

                instance.name = entry.name;
                instance.transform.localPosition = ToVector(entry.position);
                instance.transform.localEulerAngles = ToVector(entry.rotation);
                instance.transform.localScale = ToVector(entry.scale, Vector3.one);
                if (string.IsNullOrEmpty(entry.pickup))
                {
                    instance.isStatic = entry.@static;
                    AddCollision(instance, entry.collider);
                }
                else
                {
                    // Never static. A pickup is the one prop in the level that is meant to
                    // stop existing, and the static flags are a promise that it will not —
                    // batched into a combined mesh, baked into the navmesh, and carved out
                    // of the walkable surface it is lying on.
                    instance.isStatic = false;
                    AttachPickup(instance, entry.pickup);
                }
                if (!string.IsNullOrEmpty(entry.layer)) SetLayer(instance, entry.layer);
                if (!string.IsNullOrEmpty(entry.tag) && entry.tag != "Untagged")
                    TrySetTag(instance, entry.tag);
            }
        }

        /// <summary>
        /// Gives a placed object something to collide with.
        ///
        /// Instantiating an FBX gives renderers and no colliders, and nothing was adding
        /// any: every tree, house, rock and the bridge could be walked straight through,
        /// and the only solid things in the level were the ground mesh and the trigger
        /// volumes. The bridge is the one that bites hardest — the terrain dives into the
        /// stream channel beneath it, so without a deck to stand on the player walks the
        /// route straight into the water.
        ///
        /// Trees get a capsule on the stem rather than a collider around their geometry.
        /// A mesh collider on a broadleaf is a four-metre canopy you cannot walk under,
        /// which would wall off most of the route.
        /// </summary>
        private static void AddCollision(GameObject instance, string kind)
        {
            if (string.IsNullOrEmpty(kind) || kind == "none") return;

            if (kind == "trunk")
            {
                var bounds = LocalBounds(instance);
                if (bounds.size.y <= 0.01f) return;

                var capsule = instance.AddComponent<CapsuleCollider>();
                capsule.direction = 1; // Y
                capsule.height = bounds.size.y;
                capsule.center = new Vector3(0f, bounds.min.y + bounds.size.y * 0.5f, 0f);
                // A fraction of the canopy, because the canopy is what the bounding box
                // measures and the trunk is what you walk into.
                capsule.radius = Mathf.Max(0.18f,
                    Mathf.Min(bounds.size.x, bounds.size.z) * 0.13f);
                return;
            }

            foreach (var filter in instance.GetComponentsInChildren<MeshFilter>(true))
            {
                if (filter.sharedMesh == null) continue;
                var collider = filter.gameObject.AddComponent<MeshCollider>();
                collider.sharedMesh = filter.sharedMesh;
                collider.convex = false;   // static geometry; concave is free here
            }
        }

        /// <summary>
        /// How far from an item ball the interaction prompt should reach, in metres.
        ///
        /// The ball's own geometry is 0.28 m across. A collider that size is a target the
        /// player has to stand on top of, and <see cref="PlayerInteractor"/> scores by the
        /// collider's *centre*, so widening the trigger moves nothing — it only decides how
        /// close you have to get before the game offers you the item.
        /// </summary>
        private const float PickupReachMetres = 0.6f;

        /// <summary>
        /// Turns a placed prop into something the player can collect.
        ///
        /// Three parts, and each of them is why the layout carries a <c>pickup</c> field at
        /// all rather than this being hand-wiring in the scene: the highlight that says the
        /// prop is an item, the trigger the interaction ray can find, and the component that
        /// actually moves it into the bag.
        ///
        /// The trigger replaces the emitted collider rather than joining it. An item ball is
        /// solid geometry standing in the middle of its own reward, so a real collider is
        /// something the player bumps into while walking up to it — and it vanishes the
        /// instant the item is taken, which is a solid the character controller was standing
        /// against one frame and through the next.
        ///
        /// The glow goes on the renderer, not on the root. <see cref="PickupGlow"/> writes a
        /// MaterialPropertyBlock, which is per renderer, and it requires one on its own
        /// GameObject; an FBX instance keeps its mesh on a child.
        /// </summary>
        private static void AttachPickup(GameObject instance, string itemId)
        {
            var bounds = LocalBounds(instance);
            var scale = Mathf.Max(0.01f, instance.transform.lossyScale.x);

            var trigger = instance.AddComponent<SphereCollider>();
            trigger.isTrigger = true;
            trigger.center = bounds.center;
            trigger.radius = Mathf.Max(bounds.extents.magnitude, PickupReachMetres / scale);

            instance.AddComponent<ItemPickup>().ItemId = itemId;

            var renderer = instance.GetComponentInChildren<Renderer>();
            if (renderer == null)
            {
                Debug.LogWarning($"[Level] {instance.name} grants '{itemId}' but has no " +
                                 "renderer to light up, so it will read as scenery.", instance);
                return;
            }
            renderer.gameObject.AddComponent<PickupGlow>();
        }

        /// <summary>Bounds of every renderer, in the instance's own space.</summary>
        private static Bounds LocalBounds(GameObject instance)
        {
            var renderers = instance.GetComponentsInChildren<Renderer>(true);
            if (renderers.Length == 0) return new Bounds(Vector3.zero, Vector3.zero);

            var toLocal = instance.transform.worldToLocalMatrix;
            var bounds = new Bounds(
                toLocal.MultiplyPoint3x4(renderers[0].bounds.center), Vector3.zero);
            foreach (var renderer in renderers)
            {
                var b = renderer.bounds;
                foreach (var corner in Corners(b))
                    bounds.Encapsulate(toLocal.MultiplyPoint3x4(corner));
            }
            return bounds;
        }

        private static IEnumerable<Vector3> Corners(Bounds b)
        {
            var min = b.min;
            var max = b.max;
            yield return new Vector3(min.x, min.y, min.z);
            yield return new Vector3(max.x, min.y, min.z);
            yield return new Vector3(min.x, min.y, max.z);
            yield return new Vector3(max.x, min.y, max.z);
            yield return new Vector3(min.x, max.y, min.z);
            yield return new Vector3(max.x, max.y, min.z);
            yield return new Vector3(min.x, max.y, max.z);
            yield return new Vector3(max.x, max.y, max.z);
        }

        /// <summary>
        /// Builds the invisible walls that close the town.
        ///
        /// The boundary wood is drawn as instanced foliage, which means it has no colliders
        /// at all — <c>Graphics.DrawMeshInstanced</c> submits geometry to the renderer and
        /// nothing else. Five hundred tree colliders would be the obvious answer and is the
        /// wrong one: it is five hundred physics bodies to stop the player walking into a
        /// wall they should never be able to reach, and the gaps between round trunks would
        /// still let them wedge through. So the wood is scenery and these boxes are the
        /// boundary, overlapped at every turn so the run has no seams.
        ///
        /// They carry no renderer deliberately. A barrier the player can see is a barrier
        /// they will test.
        /// </summary>
        private static void BuildBarriers(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var volume in layout.barrierVolumes ?? Array.Empty<BarrierVolume>())
            {
                var go = new GameObject(volume.name);
                go.transform.SetParent(ResolveParent(root, parents, "Barriers"), false);
                go.transform.localPosition = ToVector(volume.centre);
                go.transform.localRotation = Quaternion.Euler(0f, volume.yawDegrees, 0f);

                var box = go.AddComponent<BoxCollider>();
                // The emitter gives full extents and sinks the box a metre into the ground,
                // so the centre is already where it belongs — no half-height offset here.
                box.size = ToVector(volume.size, Vector3.one);

                SetLayer(go, string.IsNullOrEmpty(volume.layer) ? "Environment" : volume.layer);
            }
        }

        private static void BuildAnchors(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var anchor in layout.ambientAnchors ?? Array.Empty<Anchor>())
            {
                // Anchors are empties. The VFX and audio directors resolve them by name and
                // attach their own emitters, so placing a live effect here would double up.
                var go = new GameObject($"Anchor_{anchor.type}_{anchor.name}");
                go.transform.SetParent(ResolveParent(root, parents, "Ambient"), false);
                go.transform.localPosition = ToVector(anchor.position);
            }
        }

        /// <summary>
        /// The marker the player rig starts from when this scene is opened on its own.
        ///
        /// Only the town layout authors one; the field's is empty, because the field is
        /// designed to be walked into rather than started in. Left at the layout's value
        /// that puts the spawn at the world origin, which on this map is open air — and a
        /// scene opened for a five-second check is exactly when nobody is watching for it.
        /// So an unspecified spawn falls back to a door: arriving on the town's doorstep is
        /// a defensible place to be when nothing said otherwise.
        /// </summary>
        private static void BuildSpawn(Layout layout, Transform root)
        {
            var spawn = new GameObject("PlayerSpawn");
            spawn.transform.SetParent(root, false);

            var authored = ToVector(layout.playerSpawn, Vector3.zero);
            if (authored == Vector3.zero)
            {
                var link = layout.sceneLinks != null && layout.sceneLinks.Length > 0
                    ? layout.sceneLinks[0]
                    : null;
                if (link != null)
                {
                    authored = ToVector(link.position)
                               + Quaternion.Euler(0f, link.facingYaw, 0f) * Vector3.back * 2.5f;
                    Debug.Log($"[Level] '{layout.scene}' authors no player spawn; using the " +
                              $"{link.name} doorway at {authored}.");
                }
                else
                {
                    Debug.LogWarning($"[Level] '{layout.scene}' has neither a player spawn nor " +
                                     "a scene link, so opening it alone drops the player at the " +
                                     "origin.");
                }
            }

            spawn.transform.localPosition = SeatOnGround(layout, authored);
        }

        private const string CastPath = "Assets/Game/Data/Story/cast.json";

        /// <summary>
        /// Stands up the markers and people the story names but the level layout does not
        /// author.
        ///
        /// The two files are written by different hands: the layout is generated from a
        /// seeded design script, while cast.json is written by whoever writes the episodes.
        /// The episodes name ten camera and actor marks and one professor; the layout knows
        /// about none of them, so every CameraTo and MoveActor beat in the opening degraded
        /// to a warning and the shot the whole town was composed around was never taken.
        ///
        /// Read here rather than folded into the emitter because these are narrative
        /// positions, not level design: they move when the script moves, and a level rebuild
        /// should not be the thing that carries a rewrite.
        /// </summary>
        private static void BuildCast(Transform root, Dictionary<string, Transform> parents)
        {
            var path = Path.Combine(Directory.GetCurrentDirectory(), CastPath);
            if (!File.Exists(path))
            {
                Debug.LogWarning($"[Level] {CastPath} not found, so the episodes' camera " +
                                 "marks and the professor will not exist and every beat that " +
                                 "names one will degrade to a warning.");
                return;
            }

            Cast cast;
            try { cast = JsonUtility.FromJson<Cast>(File.ReadAllText(path)); }
            catch (Exception e)
            {
                Debug.LogWarning($"[Level] cast.json would not parse: {e.Message}");
                return;
            }

            var marks = 0;
            foreach (var marker in cast?.markers ?? Array.Empty<CastMarker>())
            {
                if (marker == null || string.IsNullOrEmpty(marker.name)) continue;
                if (GameObject.Find(marker.name) != null) continue;

                var go = new GameObject(marker.name);
                go.transform.SetParent(ResolveParent(root, parents, "Story/Marks"), false);
                // Authored heights are eye or head height for a camera to look at, so these
                // are taken as written rather than seated on the ground like a prop.
                go.transform.localPosition = ToVector(marker.position);
                marks++;
            }

            var people = 0;
            foreach (var speaker in cast?.speakers ?? Array.Empty<CastSpeaker>())
            {
                var required = speaker?.requiredNpc;
                if (required == null || string.IsNullOrEmpty(required.name)) continue;
                if (GameObject.Find(required.name) != null) continue;

                var go = new GameObject(required.name);
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/Npcs"), false);
                go.transform.localPosition = ToVector(required.position);
                go.transform.localEulerAngles = ToVector(required.rotation);

                var body = go.AddComponent<CapsuleCollider>();
                body.height = 1.7f;
                body.radius = 0.28f;
                body.center = new Vector3(0f, 0.85f, 0f);

                go.AddComponent<NpcController>()
                  .Configure(required.npcId, required.displayName, null);
                AttachSprite(go, speaker.spriteKey, required.name);
                SetLayer(go, "Interactable");
                TrySetTag(go, "Interactable");
                people++;
            }

            if (marks + people > 0)
                Debug.Log($"[Level] Cast: {marks} marker(s) and {people} authored person/people.");
        }

        [Serializable] private sealed class Cast
        {
            public CastSpeaker[] speakers;
            public CastMarker[] markers;
        }

        [Serializable] private sealed class CastMarker
        {
            public string name;
            public float[] position;
        }

        [Serializable] private sealed class CastSpeaker
        {
            public string spriteKey;
            public RequiredNpc requiredNpc;
        }

        [Serializable] private sealed class RequiredNpc
        {
            public string name;
            public string npcId;
            public string displayName;
            public float[] position;
            public float[] rotation;
        }

        // --- helpers ---------------------------------------------------------------------

        private static Transform ResolveParent(Transform root,
            Dictionary<string, Transform> parents, string path)
        {
            if (string.IsNullOrEmpty(path)) return root;
            if (parents.TryGetValue(path, out var found)) return found;

            var current = root;
            var accumulated = "";
            foreach (var part in path.Split('/'))
            {
                if (string.IsNullOrEmpty(part)) continue;
                accumulated = string.IsNullOrEmpty(accumulated) ? part : accumulated + "/" + part;
                if (!parents.TryGetValue(accumulated, out var next))
                {
                    next = new GameObject(part).transform;
                    next.SetParent(current, false);
                    parents[accumulated] = next;
                }
                current = next;
            }
            return current;
        }

        /// <summary>
        /// Layers that were asked for but do not exist, reported once per build rather
        /// than once per object.
        ///
        /// This used to return silently, and that silence cost a great deal. `Ground`,
        /// `Environment` and `ZoneTrigger` are all named in <c>OverworldNames</c> and were
        /// never added to TagManager, so every ground chunk and every prop in the level
        /// landed on Default. The navmesh bake masks on exactly those layers, so it was
        /// baking over an empty set — which surfaced as "Failed to create agent because it
        /// is not close enough to the NavMesh" and read like an NPC placement fault, when
        /// in fact there was no walkable surface anywhere in the scene.
        /// </summary>
        private static readonly HashSet<string> MissingLayers = new HashSet<string>();

        private static void SetLayer(GameObject go, string layerName)
        {
            var layer = LayerMask.NameToLayer(layerName);
            if (layer < 0)
            {
                if (MissingLayers.Add(layerName))
                {
                    Debug.LogWarning(
                        $"[Level] Layer '{layerName}' is not declared, so everything the " +
                        "layout assigns to it stays on Default. Physics queries and the " +
                        "navmesh bake filter on these names — add it under Tags and Layers.");
                }
                return;
            }
            foreach (var t in go.GetComponentsInChildren<Transform>(true)) t.gameObject.layer = layer;
        }

        private static void TrySetTag(GameObject go, string tag)
        {
            try { go.tag = tag; }
            catch (UnityException) { /* Undeclared tags are not worth failing a build over. */ }
        }

        private static Vector3 ToVector(float[] v, Vector3 fallback = default) =>
            v != null && v.Length >= 3 ? new Vector3(v[0], v[1], v[2]) : fallback;

        // --- serialized shapes, matching emit_unity_layout.py ------------------------------

        [Serializable]
        private sealed class Layout
        {
            public string schema;
            public string scene;
            public HeightGrid heightGrid;
            public GroundChunk[] ground;
            public WaterSurface[] water;
            public FoliageField[] foliage;
            public Placement[] objects;
            public Anchor[] ambientAnchors;
            public GrassTrigger[] tallGrass;
            public CaveEntrance[] caveEntrances;
            public BarrierVolume[] barrierVolumes;
            public SceneLink[] sceneLinks;
            public NpcRecord[] npcs;
            public TrainerRecord[] trainers;
            public float[] playerSpawn;
            public float cameraYaw;
            public float cameraPitch;
            public float cameraDistance;
            public float cameraFov;
        }

        [Serializable]
        private sealed class HeightGrid
        {
            public float originX;
            public float originZ;
            public float step = 1f;
            public int countX;
            public int countZ;
            public float[] heights;
        }

        [Serializable]
        private sealed class GroundChunk
        {
            public string name;
            public float[] vertices;
            public float[] normals;
            public float[] colors;
            public float[] uvs;
            public int[] triangles;
        }

        [Serializable]
        private sealed class WaterSurface
        {
            public string name;
            public string kind;
            public float surfaceY;
            public float[] vertices;
            public float[] uvs;
            public int[] triangles;
        }

        [Serializable]
        private sealed class FoliageField
        {
            public string name;
            public string kind;
            public string parent;
            public bool generatesEncounters;
            public FoliageGroup[] groups;
        }

        [Serializable]
        private sealed class FoliageGroup
        {
            public string prefab;
            public float[] instances;
        }

        [Serializable]
        private sealed class GrassTrigger
        {
            public string name;
            public float[] centre;
            public float[] triggerSize;
            public int clumpCount;
            public bool generatesEncounters;
        }

        [Serializable]
        private sealed class CaveEntrance
        {
            public string name;
            public string scene;
            public float[] position;
            public float facingYaw;
            public float[] size;
        }

        [Serializable]
        private sealed class BarrierVolume
        {
            public string name;
            public float[] centre;
            public float[] size;
            public float yawDegrees;
            public string layer;
        }

        [Serializable]
        private sealed class NpcRecord
        {
            public string name;
            public string spriteKey;
            public string npcId;
            public string displayName;
            public float[] position;
            public float[] rotation;
            public ScheduleRecord[] schedule;
        }

        [Serializable]
        private sealed class ScheduleRecord
        {
            public float startHour;
            public string activity;
            public float[] waypoint;
            public float wanderRadius;
        }

        [Serializable]
        private sealed class TrainerRecord
        {
            public string name;
            public string spriteKey;
            public string trainerId;
            public float[] position;
            public float[] rotation;
            public float sightRange;
            public float sightHalfAngle;
        }

        [Serializable]
        private sealed class SceneLink
        {
            public string name;
            public string scene;
            public string arrivalSpawn;
            public float[] position;
            public float facingYaw;
            public float[] size;
        }

        [Serializable]
        private sealed class Placement
        {
            public string prefab;
            public string name;
            public string parent;
            public float[] position;
            public float[] rotation;
            public float[] scale;
            public string layer;
            public string tag;
            public string collider;
            /// <summary>Item id this prop grants when collected. Empty for ordinary scenery.</summary>
            public string pickup;
            public bool @static;
        }

        [Serializable]
        private sealed class Anchor
        {
            public string name;
            public string type;
            public float[] position;
        }
    }
}
