using System;
using System.Collections.Generic;
using System.IO;
using PokeLab.Overworld;
using UnityEditor;
using UnityEngine;

namespace PokeLab.Boot.Editor
{
    /// <summary>
    /// Builds the playable scene from the designed layout.
    ///
    /// The layout is data, not a scene, deliberately: it is generated by a seeded script
    /// and regenerated whenever the design changes, so hand-placing it once would throw
    /// that away. This reads the flattened form produced by
    /// <c>Tools/Level/emit_unity_layout.py</c> and rebuilds the whole thing in one pass.
    ///
    /// The terrain arrives as one continuous surface split into chunks, sampled from the
    /// baked height grid that every object's Y was taken from. It used to arrive as flat
    /// polygonal "decks" held at a constant height, which is why the world looked like
    /// plates laid on top of each other; there is no deck concept in the design and there
    /// is none here now.
    ///
    /// Normals come from the emitter rather than from RecalculateNormals, because each
    /// chunk would otherwise compute a one-sided derivative along its shared edge and
    /// leave a lighting seam on every chunk boundary.
    /// </summary>
    public static class LevelLayoutBuilder
    {
        private const string LayoutPath = "Assets/Game/Data/Levels/slice_layout_unity.json";
        private const string RootName = "Level";

        private const string TerrainMaterial =
            "Assets/Game/Art/Environment/Terrain/Materials/M_Ground_TerrainBlend.mat";
        private const string WaterMaterial =
            "Assets/Game/Shaders/Materials/M_Water_Lake.mat";
        private const string FoliageMaterial =
            "Assets/Game/Art/Environment/Foliage/Materials/M_Env_Foliage.mat";

        [MenuItem("Tools/Poké Lab/Level/Build Slice Layout")]
        public static void Build()
        {
            if (!File.Exists(LayoutPath))
            {
                Debug.LogError($"[Level] {LayoutPath} not found. Run Tools/Level/emit_unity_layout.py first.");
                return;
            }

            var layout = JsonUtility.FromJson<Layout>(File.ReadAllText(LayoutPath));
            if (layout == null || layout.ground == null || layout.ground.Length == 0)
            {
                Debug.LogError("[Level] Layout parsed but carried no ground. Expected " +
                               "schema pokelab-level-unity/2 — re-run the emitter.");
                return;
            }

            var existing = GameObject.Find(RootName);
            if (existing != null) UnityEngine.Object.DestroyImmediate(existing);

            var root = new GameObject(RootName);
            var parents = new Dictionary<string, Transform>();
            var missing = new HashSet<string>();
            var stats = new Stats();

            try
            {
                BuildGround(layout, root.transform, parents);
                BuildWater(layout, root.transform, parents);
                BuildObjects(layout, root.transform, parents, missing);
                BuildFoliage(layout, root.transform, parents, missing, stats);
                BuildTallGrass(layout, root.transform, parents);
                BuildCaveEntrances(layout, root.transform, parents);
                BuildAnchors(layout, root.transform, parents);
                BuildSpawn(layout, root.transform);
            }
            finally
            {
                EditorUtility.ClearProgressBar();
            }

            if (missing.Count > 0)
            {
                Debug.LogWarning($"[Level] {missing.Count} asset path(s) could not be loaded. " +
                                 "Those entries were skipped:\n  " + string.Join("\n  ", missing));
            }

            Debug.Log(
                $"[Level] Built '{RootName}': {layout.ground.Length} ground chunks " +
                $"({stats.GroundTriangles} tris), {layout.water?.Length ?? 0} water, " +
                $"{layout.objects?.Length ?? 0} objects, {stats.FoliageInstances} foliage " +
                $"instances in {stats.FoliageGroups} instanced group(s), " +
                $"{layout.tallGrass?.Length ?? 0} grass triggers, " +
                $"{layout.caveEntrances?.Length ?? 0} cave entrance(s), " +
                $"{layout.ambientAnchors?.Length ?? 0} anchors.");
        }

        private sealed class Stats
        {
            public int GroundTriangles;
            public int FoliageInstances;
            public int FoliageGroups;
        }

        // --- terrain ------------------------------------------------------------------

        private static void BuildGround(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            var material = AssetDatabase.LoadAssetAtPath<Material>(TerrainMaterial);
            var parent = ResolveParent(root, parents, "Terrain/Ground");

            foreach (var chunk in layout.ground)
            {
                var mesh = new Mesh { name = chunk.name };
                mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;

                var count = chunk.vertices.Length / 3;
                var verts = new Vector3[count];
                var norms = new Vector3[count];
                var cols = new Color[count];
                var uvs = new Vector2[count];

                for (var i = 0; i < count; i++)
                {
                    verts[i] = new Vector3(chunk.vertices[i * 3],
                                           chunk.vertices[i * 3 + 1],
                                           chunk.vertices[i * 3 + 2]);
                    norms[i] = new Vector3(chunk.normals[i * 3],
                                           chunk.normals[i * 3 + 1],
                                           chunk.normals[i * 3 + 2]);
                    // RGBA are the terrain shader's grass / dirt / sand / rock weights.
                    // The roads live in here rather than as their own meshes, which is
                    // why there is nothing to z-fight along 191 m of road.
                    cols[i] = new Color(chunk.colors[i * 4], chunk.colors[i * 4 + 1],
                                        chunk.colors[i * 4 + 2], chunk.colors[i * 4 + 3]);
                    uvs[i] = new Vector2(chunk.uvs[i * 2], chunk.uvs[i * 2 + 1]);
                }

                mesh.vertices = verts;
                mesh.normals = norms;
                mesh.colors = cols;
                mesh.uv = uvs;
                mesh.triangles = chunk.triangles;
                mesh.RecalculateTangents();
                mesh.RecalculateBounds();

                var go = new GameObject(chunk.name);
                go.transform.SetParent(parent, false);
                go.AddComponent<MeshFilter>().sharedMesh = mesh;
                var renderer = go.AddComponent<MeshRenderer>();
                if (material != null) renderer.sharedMaterial = material;
                go.AddComponent<MeshCollider>().sharedMesh = mesh;

                go.isStatic = true;
                SetLayer(go, "Ground");
            }
        }

        private static void BuildWater(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            var material = AssetDatabase.LoadAssetAtPath<Material>(WaterMaterial);
            var parent = ResolveParent(root, parents, "Terrain/Water");

            foreach (var body in layout.water ?? Array.Empty<WaterSurface>())
            {
                var mesh = new Mesh { name = body.name };
                mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;

                var count = body.vertices.Length / 3;
                var verts = new Vector3[count];
                var uvs = new Vector2[count];
                for (var i = 0; i < count; i++)
                {
                    verts[i] = new Vector3(body.vertices[i * 3],
                                           body.vertices[i * 3 + 1],
                                           body.vertices[i * 3 + 2]);
                    uvs[i] = new Vector2(body.uvs[i * 2], body.uvs[i * 2 + 1]);
                }

                mesh.vertices = verts;
                mesh.uv = uvs;
                mesh.triangles = body.triangles;
                mesh.RecalculateNormals();
                mesh.RecalculateTangents();
                mesh.RecalculateBounds();

                var go = new GameObject(body.name);
                go.transform.SetParent(parent, false);
                go.AddComponent<MeshFilter>().sharedMesh = mesh;
                var renderer = go.AddComponent<MeshRenderer>();
                if (material != null) renderer.sharedMaterial = material;

                // A trigger, not a solid: the surf/fishing triggers read it and the player
                // is stopped by the bank, which is terrain, not by the water itself.
                var collider = go.AddComponent<MeshCollider>();
                collider.sharedMesh = mesh;
                collider.convex = false;

                go.isStatic = true;
                SetLayer(go, "Water");
            }
        }

        // --- scattered detail ------------------------------------------------------------

        private static void BuildFoliage(Layout layout, Transform root,
            Dictionary<string, Transform> parents, HashSet<string> missing, Stats stats)
        {
            if (layout.foliage == null) return;
            var material = AssetDatabase.LoadAssetAtPath<Material>(FoliageMaterial);
            if (material == null)
            {
                missing.Add(FoliageMaterial);
                return;
            }

            foreach (var field in layout.foliage)
            {
                if (field.groups == null || field.groups.Length == 0) continue;

                var host = new GameObject(field.name);
                host.transform.SetParent(
                    ResolveParent(root, parents, string.IsNullOrEmpty(field.parent)
                        ? "Terrain/Foliage" : field.parent), false);
                SetLayer(host, "Environment");
                var renderer = host.AddComponent<InstancedFoliage>();

                foreach (var group in field.groups)
                {
                    var mesh = LoadFirstMesh(group.prefab);
                    if (mesh == null)
                    {
                        missing.Add(group.prefab);
                        continue;
                    }

                    // Five floats per instance: x, y, z, yaw, uniform scale.
                    var stride = 5;
                    var count = group.instances.Length / stride;
                    var transforms = new List<Matrix4x4>(count);
                    for (var i = 0; i < count; i++)
                    {
                        var o = i * stride;
                        transforms.Add(Matrix4x4.TRS(
                            new Vector3(group.instances[o], group.instances[o + 1], group.instances[o + 2]),
                            Quaternion.Euler(0f, group.instances[o + 3], 0f),
                            Vector3.one * group.instances[o + 4]));
                    }

                    renderer.SetGroup(mesh, material, transforms);
                    stats.FoliageInstances += count;
                    stats.FoliageGroups++;
                }
            }
        }

        /// <summary>
        /// Pulls the mesh out of an imported FBX. Instancing needs the mesh and a shared
        /// material, not a prefab: a prefab would drag along its own renderer settings and
        /// there would be nothing to instance.
        /// </summary>
        private static Mesh LoadFirstMesh(string path)
        {
            foreach (var asset in AssetDatabase.LoadAllAssetsAtPath(path))
                if (asset is Mesh mesh) return mesh;
            return null;
        }

        private static void BuildTallGrass(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var patch in layout.tallGrass ?? Array.Empty<GrassTrigger>())
            {
                var go = new GameObject(patch.name);
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/TallGrass"), false);
                go.transform.localPosition = ToVector(patch.centre);

                var box = go.AddComponent<BoxCollider>();
                box.size = ToVector(patch.triggerSize, Vector3.one);
                box.isTrigger = true;

                go.AddComponent<PokeLab.Overworld.TallGrassPatch>();
                SetLayer(go, "ZoneTrigger");
            }
        }

        private static void BuildCaveEntrances(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var entrance in layout.caveEntrances ?? Array.Empty<CaveEntrance>())
            {
                // Caves are their own scenes, so the overworld carries only the doorway.
                // Nothing inside a cave is emitted into this build at all: the height grid
                // describes the mountain's outside, so an interior prop placed here would
                // sit on the summit above the chamber it belongs to.
                var go = new GameObject($"CaveEntrance_{entrance.name}");
                go.transform.SetParent(ResolveParent(root, parents, "Gameplay/Transitions"), false);
                go.transform.localPosition = ToVector(entrance.position);
                go.transform.localEulerAngles = new Vector3(0f, entrance.facingYaw, 0f);

                var box = go.AddComponent<BoxCollider>();
                box.size = ToVector(entrance.size, Vector3.one);
                box.center = new Vector3(0f, box.size.y * 0.5f, 0f);
                box.isTrigger = true;

                SetLayer(go, "ZoneTrigger");
            }
        }

        // --- props, anchors, spawn -------------------------------------------------------

        private static void BuildObjects(Layout layout, Transform root,
            Dictionary<string, Transform> parents, HashSet<string> missing)
        {
            var objects = layout.objects ?? Array.Empty<Placement>();
            var cache = new Dictionary<string, GameObject>();

            for (var i = 0; i < objects.Length; i++)
            {
                if ((i & 127) == 0 &&
                    EditorUtility.DisplayCancelableProgressBar(
                        "Building level", $"{i} / {objects.Length}", i / (float)objects.Length))
                {
                    Debug.LogWarning("[Level] Build cancelled; the scene is incomplete.");
                    return;
                }

                var entry = objects[i];
                if (string.IsNullOrEmpty(entry.prefab)) continue;

                if (!cache.TryGetValue(entry.prefab, out var prefab))
                {
                    prefab = AssetDatabase.LoadAssetAtPath<GameObject>(entry.prefab);
                    cache[entry.prefab] = prefab;
                }

                if (prefab == null)
                {
                    missing.Add(entry.prefab);
                    continue;
                }

                var instance = (GameObject)PrefabUtility.InstantiatePrefab(
                    prefab, ResolveParent(root, parents, entry.parent));
                if (instance == null) continue;

                instance.name = entry.name;
                instance.transform.localPosition = ToVector(entry.position);
                instance.transform.localEulerAngles = ToVector(entry.rotation);
                instance.transform.localScale = ToVector(entry.scale, Vector3.one);
                instance.isStatic = entry.@static;
                if (!string.IsNullOrEmpty(entry.layer)) SetLayer(instance, entry.layer);
                if (!string.IsNullOrEmpty(entry.tag) && entry.tag != "Untagged")
                    TrySetTag(instance, entry.tag);
            }
        }

        private static void BuildAnchors(Layout layout, Transform root,
            Dictionary<string, Transform> parents)
        {
            foreach (var anchor in layout.ambientAnchors ?? Array.Empty<Anchor>())
            {
                // Anchors are empties. The VFX and audio directors resolve them by name and
                // attach their own emitters, so placing a live effect here would double up.
                var go = new GameObject($"Anchor_{anchor.type}_{anchor.name}");
                go.transform.SetParent(ResolveParent(root, parents, "Ambient"), false);
                go.transform.localPosition = ToVector(anchor.position);
            }
        }

        private static void BuildSpawn(Layout layout, Transform root)
        {
            var spawn = new GameObject("PlayerSpawn");
            spawn.transform.SetParent(root, false);
            spawn.transform.localPosition = ToVector(layout.playerSpawn);
        }

        // --- helpers ---------------------------------------------------------------------

        private static Transform ResolveParent(Transform root,
            Dictionary<string, Transform> parents, string path)
        {
            if (string.IsNullOrEmpty(path)) return root;
            if (parents.TryGetValue(path, out var found)) return found;

            var current = root;
            var accumulated = "";
            foreach (var part in path.Split('/'))
            {
                if (string.IsNullOrEmpty(part)) continue;
                accumulated = string.IsNullOrEmpty(accumulated) ? part : accumulated + "/" + part;
                if (!parents.TryGetValue(accumulated, out var next))
                {
                    next = new GameObject(part).transform;
                    next.SetParent(current, false);
                    parents[accumulated] = next;
                }
                current = next;
            }
            return current;
        }

        private static void SetLayer(GameObject go, string layerName)
        {
            var layer = LayerMask.NameToLayer(layerName);
            if (layer < 0) return;
            foreach (var t in go.GetComponentsInChildren<Transform>(true)) t.gameObject.layer = layer;
        }

        private static void TrySetTag(GameObject go, string tag)
        {
            try { go.tag = tag; }
            catch (UnityException) { /* Undeclared tags are not worth failing a build over. */ }
        }

        private static Vector3 ToVector(float[] v, Vector3 fallback = default) =>
            v != null && v.Length >= 3 ? new Vector3(v[0], v[1], v[2]) : fallback;

        // --- serialized shapes, matching emit_unity_layout.py ------------------------------

        [Serializable]
        private sealed class Layout
        {
            public string schema;
            public GroundChunk[] ground;
            public WaterSurface[] water;
            public FoliageField[] foliage;
            public Placement[] objects;
            public Anchor[] ambientAnchors;
            public GrassTrigger[] tallGrass;
            public CaveEntrance[] caveEntrances;
            public float[] playerSpawn;
            public float cameraYaw;
            public float cameraPitch;
            public float cameraDistance;
            public float cameraFov;
        }

        [Serializable]
        private sealed class GroundChunk
        {
            public string name;
            public float[] vertices;
            public float[] normals;
            public float[] colors;
            public float[] uvs;
            public int[] triangles;
        }

        [Serializable]
        private sealed class WaterSurface
        {
            public string name;
            public string kind;
            public float surfaceY;
            public float[] vertices;
            public float[] uvs;
            public int[] triangles;
        }

        [Serializable]
        private sealed class FoliageField
        {
            public string name;
            public string kind;
            public string parent;
            public bool generatesEncounters;
            public FoliageGroup[] groups;
        }

        [Serializable]
        private sealed class FoliageGroup
        {
            public string prefab;
            public float[] instances;
        }

        [Serializable]
        private sealed class GrassTrigger
        {
            public string name;
            public float[] centre;
            public float[] triggerSize;
            public int clumpCount;
            public bool generatesEncounters;
        }

        [Serializable]
        private sealed class CaveEntrance
        {
            public string name;
            public string scene;
            public float[] position;
            public float facingYaw;
            public float[] size;
        }

        [Serializable]
        private sealed class Placement
        {
            public string prefab;
            public string name;
            public string parent;
            public float[] position;
            public float[] rotation;
            public float[] scale;
            public string layer;
            public string tag;
            public bool @static;
        }

        [Serializable]
        private sealed class Anchor
        {
            public string name;
            public string type;
            public float[] position;
        }
    }
}
